<div class="headerOffset">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<center>
                            <h1 class="section-title-inner"><span>Hola, <?php echo ucfirst($this->user->firstname).' '.ucfirst($this->user->lastname) ?></span></h1>
				<h6 class="section-title-inner"><span>Ult vez conectado: XX / XX / XXXX - 12:00 pm</span></h6>
			</center>
		</div>
		<br><br>
                <h1>HOLA MUNDO!</h1>
		<br><br>
		<center>
			<a href="<?php echo $this->url('account', array('controller' => 'login', 'action' => 'logout')) ?>">
				<button class="btn btn-primary" type="submit">Salir</button>
			</a>
		</center>
    </div>
</div>
<div class="gap"> </div>