<div>
<div>  
<table style="width:100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f6f4f5"><tbody><tr><td>
<table style="width:580px;margin-top: 15px;" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"><tbody><tr><td>
<table style="width:280px" border="0" cellspacing="0" cellpadding="0" align="left"><tbody><tr><td style="padding:15px 0 15px 20px" width="270">
<div><a href="http://www.lakarihome.com" target="_blank"><img style="border:none;text-decoration:none" src="http://www.lakarihome.com/images/lakarihome-logo.png" alt="logo" border="0" class="CToWUd"></a>
<a href="https://es-es.facebook.com/Lakarihome" target="_blank"><img style="border:none;text-decoration:none; padding-left: 180px;" src="http://www.lakarihome.com/images/facebook_icon.png" alt="logo" border="0" class="CToWUd"></a>
<a href="https://twitter.com/lakarihome" target="_blank"><img style="border:none;text-decoration:none;  padding-left: 30px; padding-right: 0.1em" src="http://www.lakarihome.com/images/twetter_icon.png" alt="logo" border="0" class="CToWUd"></a>
<a href="https://instagram.com/lakarihome/" target="_blank"><img style="border:none;text-decoration:none;  padding-left: 30px; padding-right: 0.1em" src="http://www.lakarihome.com/images/instagram_icon.png" alt="logo" border="0" class="CToWUd"></a>
<a href="http://www.pinterest.com" target="_blank"><img style="border:none;text-decoration:none;  padding-left: 30px; padding-right: 0.1em" src="http://www.lakarihome.com/images/pinteres_icon.png" alt="logo" border="0" class="CToWUd"></a><hr style="padding:0; margin-top: 10px; width:520px; align:center;"></div>
</td>
</tr></tbody></table></td>
</tr></tbody></table></td>
</tr></tbody></table></div>
<div>
<table style="width:100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f6f4f5"><tbody><tr><td>
<table style="width:580px;margin-bottom: 15px" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"><tbody><tr><td width="100%" height="20">&nbsp;</td>
</tr><tr><td>
<table style="width:540px" border="0" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:34px;color:#245273;text-align:center;line-height:34px">Hola!</td>
        </tr><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:22px;color:#333333;text-align:center;line-height:34px"><?php echo ucfirst($this->customer->firstname) ?> estas a solo un paso...</td>
</tr><tr><td width="100%" height="20">&nbsp;</td>
</tr><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:13px;color:#666666;text-align:left;line-height:18px">
<p>Estamos contentos por haber elegido PideRapido.com. <br> Confirme su dirección de correo electrónico, para completar su registro!</p>
</td>
</tr><tr><td width="100%" height="20">&nbsp;</td>
</tr><tr><td>
<table border="0" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="background-color:#585858;text-transform:uppercase;letter-spacing:1px;font-size:13px;font-family:Helvetica,arial,sans-serif;text-align:center;color:#ffffff;font-weight:400;padding-left:25px;padding-right:25px" align="center" valign="middle" height="36"><span style="color:#ffffff;font-weight:400"> 
                    <a style="color:#ffffff;text-align:center;text-decoration:none" href="<?php echo $this->link ?>" target="_blank">CONFIRMAR EMAIL</a> </span></td>
</tr></tbody></table></td>
</tr><tr><td width="100%" height="20">&nbsp;</td>
</tr><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:13px;color:#666666;text-align:left;line-height:18px">
<p>En caso de que el botón no funcione, por favor copie el siguiente enlace en su navegador:</p>
<p><a href="<?php echo $this->link ?>" target="_blank"><?php echo $this->link ?></a></p>
<p><span style="color:#666666;font-family:Helvetica,arial,sans-serif;font-size:13px;line-height:18px">Que tenga un buen día</span>,<br> El equipo de Pide<strong>Rapido</strong>.com</p>
</td>
</tr><tr><td width="100%" height="20">&nbsp;</td>
</tr><tr><td style="font-family:Helvetica,arial,sans-serif;font-size:11px;color:#666666;text-align:left;line-height:11px">En caso de recibir este mensaje por error, no es necesario tomar ninguna otra medida, no recibirá ningún envío automatizado. Si cree que su dirección de correo electrónico fue mal utilizado, por favor contacte con nosotros en <a href="mailto:info@piderapido.com" target="_blank">info@piderapido.com</a>.</td>
</tr><tr><td width="100%" height="20">&nbsp;</td>
</tr></tbody></table></td>
</tr></tbody></table></td>
</tr></tbody></table></div>
</div>

