
<?php //var_dump($this->products); ?>
<div class="row outer-bottom-sm">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-3 sidebar">
            <!-- ================================== TOP NAVIGATION ================================== -->
            <div class="side-menu side-menu2 animate-dropdown outer-bottom-xs">
                <strong>Module:</strong>        Catalog &raquo;
                <strong>Controller:</strong>    Index &raquo;
                <strong>Action:</strong>        index

            </div>
        </div>
        
    </div>
</div>


