<?php
$this->headlink()
        
        ->prependStylesheet($this->basePath() . '/vendor/plugins/select2/css/core.css');
?>
<!-- Start: Topbar -->
<header id="topbar" class="ph10">
    <div class="topbar-left">
        <ul class="nav nav-list nav-list-topbar pull-left">
            <li>
                <a href="#">Dashboard</a>
            </li>            
            <li class="active">
                <a href="<?php echo $this->url('admin', array('controller' => 'provider', 'action' => 'list')); ?>.html">Compañias</a>
            </li>

        </ul>
    </div>
    <!--    <div class="topbar-right hidden-xs hidden-sm">
          
            <a href="ecommerce_products.html" class="btn btn-default btn-sm light fw600 ml10">
                <span class="fa fa-plus pr5"></span> Add Product</a>
            <a href="ecommerce_customers.html" class="btn btn-default btn-sm light fw600 ml10">
                <span class="fa fa-user pr5"></span> Add Company</a>
        </div>-->
</header>
<!-- End: Topbar -->

<!-- Begin: Content -->
<section id="content" class="table-layout animated fadeIn">

    <!-- begin: .tray-center -->
    <div class="tray tray-center">
         <?php if($this->save == 1) {
                        $message = "Provedor <strong> Creado </strong> satisfactoriamente";
                        echo $this->alert('succes',$message);
                    }
                ?>
        <!-- create new order panel -->
        <div class="panel mb25 mt5">
            <div class="panel-heading">
                <span class="panel-title hidden-xs"> Agregar Nuevo Provedor</span>
                <ul class="nav panel-tabs-border panel-tabs">
                    <li class="active">
                        <a href="#tab1_1" data-toggle="tab">General</a>
                    </li>
                    <li>
                        <a href="#tab1_2" data-toggle="tab">Configuración</a>
                    </li>
                    <!--li>
                        <a href="#tab1_3" data-toggle="tab">Dirección</a>
                    </li-->
                </ul>
            </div>
            <div class="panel-body p20 pb10 form-horizontal">
                <form id="form"  action="<?php echo $this->basePath($this->providerForm->getAttribute('action')); ?>" method="post" enctype="multipart/form-data" >   

                    <div class="tab-content pn br-n admin-form">
                        <div id="tab1_1" class="tab-pane active">

                            <div class="section row mbn">
                                <div class="col-md-2">
                                    <div class="fileupload fileupload-new admin-form" data-provides="fileupload">
                                        <div class="fileupload-new thumbnail" style="">
                                            <img data-src="holder.js/200x100/text:logo" src="" />
                                        </div>
                                        <div class="fileupload-preview fileupload-exists thumbnail" style=""></div>
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <span class="button btn-system btn-file btn-block">
                                                    <span class="fileupload-new">Select</span>
                                                    <span class="fileupload-exists">Change</span>
                                                    <?php echo $this->formFile($this->providerForm->get('logo')); ?>

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-10 ">
                                    <div class="section row  form-group">
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="company">Compañia <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="company" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->providerForm->get('company')); ?>
                                                    <label for="company" class="field-icon"><i class="fa fa-user"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->providerForm->get('company')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="company_id">ID Fiscal <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="company_id" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->providerForm->get('company_id')); ?>
                                                    <label for="company_id" class="field-icon"><i class="fa fa-barcode"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->providerForm->get('company_id')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="section row form-group">
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="email">Email <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="email" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->providerForm->get('email')); ?>
                                                    <label for="email" class="field-icon"><i class="fa fa-envelope-o"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->providerForm->get('email')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-6">
                                             <label class="col-md-3 control-label" for="email">Confirmar Email <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="confirmemail" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->providerForm->get('confirmEmail')); ?>
                                                    <label for="confirmemail" class="field-icon"><i class="fa fa-envelope-o"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->providerForm->get('confirmEmail')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="section row form-group">
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="password">Clave <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="password" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->providerForm->get('password')); ?>
                                                    <label for="password" class="field-icon"><i class="fa fa-lock"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->providerForm->get('password')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-6">
                                             <label class="col-md-3 control-label" for="confirmarPassword">Confirmar Clave<span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="confirmarPassword" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->providerForm->get('confirmarPassword')); ?>
                                                    <label for="confirmarPassword" class="field-icon"><i class="fa fa-lock"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->providerForm->get('confirmarPassword')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="section row form-group">
                                        <div class="col-xs-6">
                                          <label class="col-lg-3 control-label" for="status">Status <span class="text-danger">*</span></label>
                                                <div class="col-md-9 "> 
                                                    <label class="field select">
                                                        <?php echo $this->formRow($this->providerForm->get('status')) ?>
                                                        <i class="arrow double "></i>
                                                    </label>
                                                    <div class="help-block">
                                                        <?php echo $this->formelementerrors($this->providerForm->get('status')) ?> 
                                                    </div>
                                                </div>
                                        </div>
                                        <div class="col-xs-6">
                                            
                                        </div>
                                    </div>
                                   
                                </div>
                                
                            </div>
                            <!-- end section row -->

                        </div>
                        <div id="tab1_2" class="tab-pane">

                            <div class="section row mbn">
                                <div class="col-xs-6 pr15">
                                    <div class="section mb10">
                                    <label class="col-lg-3 control-label" for="categories">Categorias  <span class="text-danger">*</span></label>
                                    <div class="col-md-9 form-group">
                                        <?php echo $this->formSelect($this->providerForm->get('categories')) ?>                                      
                                    </div>
                                    </div>                                   
                                    <div class="section">
                                     <label class="col-lg-3 control-label" for="stock">Stock  <span class="text-danger">*</span></label>
                                    <div class="col-md-9 form-group">
                                        <?php echo $this->formSelect($this->providerForm->get('store_id')) ?>                                      
                                    </div>
                                    </div>
                                    <div class="section mb10">
                                        <label class="col-lg-3 control-label" for="grupo">Grupo <span class="text-danger">*</span></label>
                                        <div class="col-md-9 "> 
                                            <label class="field select">
                                                <?php echo $this->formRow($this->providerForm->get('provider_group_id')) ?>
                                                <i class="arrow double "></i>
                                            </label>
                                            <div class="help-block">
                                                <?php echo $this->formelementerrors($this->providerForm->get('provider_group_id')) ?> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <label class="field option ">
                                        <input type="checkbox" name="pp" checked>
                                        <span class="checkbox mr10"></span> Publicar Productos
                                    </label>
                                     <br>
                                    <label class="field option">
                                        <input type="checkbox" name="gp" checked="">
                                        <span class="checkbox mr10"></span> Generar Pedidos
                                    </label>
                                    <br>
                                    <label class="field option ">
                                        <input type="checkbox" name="ii">
                                        <span class="checkbox mr10"></span> Incluir Impuesto
                                    </label>
                                   
                                    
                                    <hr class="alt short mv15">
                                    <p class="text-muted">
                                        <span class="fa fa-exclamation-circle text-warning fs15 pr5"></span> Accesos a la tienda.</p>
                                </div>
                            </div>

                           

                            <!--div class="section mb15">
                                <label class="field prepend-icon">
                                    <textarea class="gui-textarea br-light bg-light" id="cust-note" name="cust-note" placeholder="Customer Notes"></textarea>
                                    <label for="cust-note" class="field-icon">
                                        <i class="fa fa-edit"></i>
                                    </label>
                                </label>
                            </div>
                            <!-- end section -->

                        </div>
                         <hr class="short alt mtn">
                        <div class="panel-footer text-right mt5">
                            <button class="btn btn-primary text-right"> Crear Provedor </button>
                        </div>
                    </div>
                     <?php echo $this->formRow($this->providerForm->get('csrf')) ?>
                </form>
            </div>
        </div>

        <!-- recent orders table -->
        <div class="panel col-lg-11 col-md-11">
            <div class="panel-menu admin-form theme-primary ">
                <div class="row">
                    <div class="col-md-4">
                        <label class="field select">
                            <select id="filter-purchases" name="filter-purchases">
                                <option value="0">Filter by Purchases</option>
                                <option value="1">1-49</option>
                                <option value="2">50-499</option>
                                <option value="1">500-999</option>
                                <option value="2">1000+</option>
                            </select>
                            <i class="arrow double"></i>
                        </label>
                    </div>
                    <div class="col-md-4">
                        <label class="field select">
                            <select id="filter-group" name="filter-group">
                                <option value="0">Filter by Group</option>
                                <option value="1">Customers</option>
                                <option value="2">Vendors</option>
                                <option value="3">Distributors</option>
                                <option value="4">Employees</option>
                            </select>
                            <i class="arrow double"></i>
                        </label>
                    </div>
                    <div class="col-md-4">
                        <label class="field select">
                            <select id="filter-status" name="filter-status">
                                <option value="0">Filter by Status</option>
                                <option value="1">Active</option>
                                <option value="2">Inactive</option>
                                <option value="3">Suspended</option>
                                <option value="4">Online</option>
                                <option value="5">Offline</option>
                            </select>
                            <i class="arrow double"></i>
                        </label>
                    </div>
                </div>
            </div>
            <div class="panel-body pn ">
                <div class="table-responsive">
                    <table class="table admin-form theme-warning tc-checkbox-1 fs13">
                        <thead>
                            <tr class="bg-light">
                                <th class="text-center">Select</th>
                                <th class="">Logo</th>
                                <th class="">Compañia</th>
                                <th class="">Compañia ID</th>
                                <th class="">Email</th>
                                <th class="">Status</th>
                                <th class="">Ingreso</th>
                                <th class="">Opciones</th>
                               

                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->provider as $provider) : ?>
                            <tr>
                                <td class="text-center">
                                    <label class="option block mn">
                                        <input type="checkbox" name="mobileos" value="FR">
                                        <span class="checkbox mn"></span>
                                    </label>
                                </td>
                                <td class="w50">
                                    <img class="img-responsive mw30 ib mr10" title="user" src="<?php echo $this->basePath().'/assets/images/providers/'.$provider->logo?>">
                                </td>
                                <td class=""><?php echo $provider->company;?></td>
                                <td class=""><?php echo $provider->company_id;?></td>
                                <td class=""><?php echo $provider->email;?></td>
                                <td class=""><?php echo $provider->status;?></td>
                                <td class=""><?php echo $provider->date_added;?></td>
                             
                                <td class="text-right">
                                    <div class="btn-group text-right">
                                        <?php switch ($provider->status) {
                                                case 1:
                                                   echo '<button type="button" class="btn btn-success br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> 
                                                            Activo
                                                            <span class="caret ml5"></span>
                                                        </button>';                 
                                                    break;
                                                case 2:
                                                    echo '<button type="button" class="btn btn-warning br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false">  
                                                            Sin Aprobar
                                                            <span class="caret ml5"></span>
                                                          </button>';
                                                    break;
                                                case 3:
                                                    echo '<button type="button" class="btn btn-danger br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                             Desactivado
                                                            <span class="caret ml5"></span>
                                                          </button>';
                                                    break;
                                                default:
                                                    echo '<button type="button" class="btn btn-danger br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> 
                                                            No confirmado
                                                            <span class="caret ml5"></span>
                                                          </button>';
                                                    break;
                                            }
                                            ?>
                                        
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="#">Editar</a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->basePath('admin/provider/productlist/').$provider->provider_id;?>">Products</a>
                                            </li>
                                            <li>
                                                <a href="#">Contacto</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li class="">
                                                <a href="#">Activo</a>
                                            </li>
                                            <li>
                                                <a href="#">Sin Aprobar</a>
                                            </li>
                                            <li>
                                                <a href="#">Desactivado</a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                     <?php endforeach; ?>        
                        </tbody>
                    </table>
                </div>
                
               <div class="text-center">
                <?php
                   // add at the end of the file after the table
                    echo $this->paginationControl(
                    // the paginator object
                    $this->provider,
                    // the scrolling style
                    'sliding',
                    // the partial to use to render the control
                    'partial/paginator.phtml',
                    // the route to link to when a user clicks a control link
                    array(
                        'route' => 'admin', 'controller' => 'provider', 'action' => 'list'
                   ));
               ?>
            </div>
            </div>
        </div>

    </div>
    <!-- end: .tray-center -->

    <!-- begin: .tray-right -->

    <!-- end: .tray-right -->

</section>
<!-- End: Content -->
<?php
$this->headScript()
        ->prependFile($this->basePath() . '/vendor/plugins/fileupload/fileupload.js')
  //      ->prependFile($this->basePath() . '/vendor/plugins/tagsinput/tagsinput.min.js')
        ->prependFile($this->basePath() . '/vendor/plugins/select2/select2.min.js')
        ->prependFile($this->basePath() . '/assets_admin/js/bootstrap/holder.min.js')
 //       ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/advanced/steps/jquery.steps.js')
        ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/jquery.validate.min.js')
// ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/additional-methods.min.js')
;
$this->inlineScript()->captureStart();
 echo <<<JS
   
    jQuery(document).ready(function() {

    // select dropdowns - placeholder like creation
    var selectList = $('.admin-form select');
    selectList.each(function(i, e) {
      $(e).on('change', function() {
        if ($(e).val() == "0") $(e).addClass("empty");
        else $(e).removeClass("empty")
      });
    });
    selectList.each(function(i, e) {
      $(e).change();
    });
    
    // Init Select2 - Basic Multiple
    $("#categories").select2({
      placeholder: "Select Categories",
       allowClear: false,
       style: "bg-primary light"
    });
    $("#stock").select2({
      placeholder: "Select stock",
       allowClear: true,
      
    });

     /* @custom validation method (smartCaptcha) 
            ------------------------------------------------------------------ */
                
            $.validator.methods.smartCaptcha = function(value, element, param) {
                    return value == param;
            };
            
            $.validator.addMethod("Alnum", function(value, element) {
             return this.optional(element) || /^[a-z0-9\s]+$/i.test(value);
            }, "Username must contain only letters, numbers, or dashes.");

            $.validator.addMethod("AlnumOf", function(value, element) {
             return this.optional(element) || /^[a-z0-9\-]+$/i.test(value);
            }, "Username must contain only letters, numbers, or dashes.");
                    
            $( "#form" ).validate({
            
                    /* @validation states + elements 
                    ------------------------------------------- */
                    
                    errorClass: "state-error",
                    validClass: "state-success",
                    errorElement: "em",
                    ignore: false,
                    
                    /* @validation rules 
                    ------------------------------------------ */
                        
                    rules: {
                            company: {
                                    required: true,
                                    Alnum: true,
                            },
                            company_id: {
                                    required: true,
                                    minlength: 2,    
                                    Alnum: true,
                            },                                                                
                            email: {
                                    required: true,
                                    email:true
                            },
                            confirmEmail: {
                                    required: true,
                                    email:true,                               
				    equalTo: "#email"
                            },
                            password: {
                                    required: true,
                                    minlength: 5,
                                    Alnum: true,
                            },
                            confirmarPassword: {
                                    required: true,
                                    AlnumOf: true,
                                    equalTo: "#password"
                            },
                            categories: {
                                    required: true
                            },  
                                
                        
                    },
                    
                    /* @validation error messages 
                    ---------------------------------------------- */
                        
                    messages:{
                            company: {
                                    required: 'Campo Obligatorio',
                                    Alnum: 'Solo letras y numeros'
                            },
                            company_id: {
                                    required: 'Campo Obligatorio',
                                    Alnum: 'Solo letras y numeros'
                            },                  
                            email: {
                                    email: 'Email Invalido',
                                    required: 'Campo Obligatorio'
                            },                  
                            confirmEmail: {
                                    email: 'Email Invalido',
                                    required: 'Campo Obligatorio',
                                    equalTo: "Email no coincide"
                            },                  
                            password: {
                                    required: 'Campo Obligatorio',
                                    Alnum: 'Solo letras y numeros'
                                    
                            },                  
                            confirmarPassword: {
                                    required: 'Campo Obligatorio',
                                    Alnum: 'Solo letras y numeros',
                                    minlength: 'Password minimo 5 caracteres',
                                    equalTo: "Password no coincide"
                                    
                            },                  
                                
                           
                    },

                    /* @validation highlighting + error placement  
                    ---------------------------------------------------- */ 
                    
                    highlight: function(element, errorClass, validClass) {
                            $(element).closest('.field').addClass(errorClass).removeClass(validClass);
                    },
                    invalidHandler: function(e,validator) {
                        // loop through the errors:                
                          $('.tab-pane').closest('.active').removeClass('active');
                          $('.panel-tabs li').closest('.active').removeClass('active');
                            // "uncollapse" section containing invalid input/s:
                            $(validator.errorList[0].element).closest('.tab-pane').addClass('active');
                            tab =  $(validator.errorList[0].element).closest('.tab-pane').attr('id');
                            tab ='#'+tab;
                          $('a[href='+tab+']').closest('li').addClass('active');
                        
                    },
                    unhighlight: function(element, errorClass, validClass) {
                            $(element).closest('.field').removeClass(errorClass).addClass(validClass);
                    },
                    errorPlacement: function(error, element) {
                       if (element.is(":radio") || element.is(":checkbox")) {
                                element.closest('.option-group').after(error);
                       } else {
                                error.insertAfter(element.parent());
                       }
                    }
                            
            });     


  });

JS;
$this->inlineScript()->captureEnd();
