<div class="row">

    <center>
        <h1 class="section-title-inner"><span>Inicia Sesión o Registrate</span></h1>

    </center>

    <div class="col-lg-12 col-md-9 col-sm-7">

        <div class="row userInfo">

            <div class="col-xs-12 col-sm-3">
                <h2 class="block-title-2"> Crear una cuenta </h2>
                <form action="<?php echo $this->url('account', array('controller' => 'register', 'action' => 'add')) ?>" method="post">     
                    <div class="form-group">
                        <label>Nombre</label>
                        <?php echo $this->formInput($this->registerForm->get('firstname')); ?>
                    </div>
                    <div class="form-group">
                        <label>Apellido</label>
                        <?php echo $this->formInput($this->registerForm->get('lastname')); ?>
                    </div>
                    <div class="form-group">
                        <label>Correo Electrónico</label>
                        <?php echo $this->formInput($this->registerForm->get('email')); ?>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <?php echo $this->formInput($this->registerForm->get('password')); ?>
                    </div>
                    <div class="form-group">
                        <label>
                            <?php echo $this->formInput($this->registerForm->get('rememberme')); ?>
                            Recordarme 
                        </label>
                    </div>


                    <button type="submit" class="btn   btn-primary">Crear una cuenta</button>
                    <?php echo $this->formInput($this->registerForm->get('csrf')); ?>	
                </form>
            </div>
            <div class="col-xs-12 col-sm-offset-1 col-sm-3">
                <h2 class="block-title-2"><span>Ya registrado?</span></h2>
                <form role="form" class="logForm">
                    <div class="form-group">
                        <label>Correo Electrónico</label>
                        <input type="email" class="form-control" placeholder="Correo Electrónico">
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <p><a title="Recover your forgotten password" href="password.php"> ¿Olvidó su contraseña? </a></p>
                    </div>
                    <a class="btn btn-primary" href="index-login.php">Iniciar Sesión</a>
                </form>
            </div>

            <div class="col-xs-12 col-sm-offset-1 col-sm-3">
                <h2 class="block-title-2"><span>Ingresa con Facebook</span></h2>
                <div class="control-group">
                    <a class="fb_button btn btn-block btn-lg " href="#"> Vía Facebook </a>
                </div>
            </div>
        </div>
        <!--/row end--> 

    </div>

</div> <!--/row-->