'use strict';

export var constants = {

    ADD_PRODUCT: 'ADD_PRODUCT',
    LIKE_PRODUCT: 'LIKE_PRODUCT',
    SHARE_PRODUCT: 'SHARE_PRODUCT',

    TOGGLE_CART: 'TOGGLE_CART',

    EXPAND_PRODUCT: 'EXPAND_PRODUCT',
    EXPAND_PRODUCT_RESPONSE: 'EXPAND_PRODUCT_RESPONSE',
    EXPAND_PRODUCT_ERROR: 'EXPAND_PRODUCT_ERROR'

};

export var events = {
    CHANGE: 'CHANGE'
}

