'use strict';

export var constants = {

    ADD_PRODUCT: 'ADD_PRODUCT',
    LIKE_PRODUCT: 'LIKE_PRODUCT',
    SHARE_PRODUCT: 'SHARE_PRODUCT',

    SHOW_CART: 'SHOW_CART',
    HIDE_CART: 'HIDE_CART',

    TOGGLE_OVERLAY: 'TOGGLE_OVERLAY',
    OVERLAY_CLICK: 'OVERLAY_CLICK',

    EXPAND_PRODUCT: 'EXPAND_PRODUCT',
    EXPAND_PRODUCT_RESPONSE: 'EXPAND_PRODUCT_RESPONSE',
    EXPAND_PRODUCT_ERROR: 'EXPAND_PRODUCT_ERROR',

    /* Admin */

    ADD_ITEM : 'ADD_ITEM',
    ITEM_ADDED: 'ITEM_ADDED',
    ITEM_INVALID: 'ITEM_INVALID',

    REMOVE_ITEM : 'REMOVE_ITEM',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    DELETE_PRODUCT_FAIL: 'DELETE_PRODUCT_FAIL',

    INCREASE_ITEM : 'INCREASE_ITEM',
    DECREASE_ITEM : 'DECREASE_ITEM',

    EMPTY_KART: 'EMPTY_KART',
    CHANGE_ITEM: 'CHANGE_ITEM',

    SELECT_USER: 'SELECT_USER',
    EDIT_USER: 'EDIT_USER',
    FETCH_USER: 'FETCH_USER',
    USER_CONFIRM: 'USER_CONFIRM',
    USER_VALID: 'USER_VALID',
    USER_INVALID: 'USER_INVALID',

    SELECT_ORDER: 'SELECT_ORDER',
    DELETE_ORDER: 'DELETE_ORDER',
    ORDER_CREATED: 'ORDER_CREATED',
    ORDER_DELETED: 'ORDER_DELETED',
    ORDER_VALID: 'ORDER_VALID',
    ORDER_INVALID: 'ORDER_INVALID',

};

export var events = {
    CHANGE: 'CHANGE'
}

