'use strict';

export var constants = {

    ADD_PRODUCT: 'ADD_PRODUCT',
    LIKE_PRODUCT: 'LIKE_PRODUCT',
    SHARE_PRODUCT: 'SHARE_PRODUCT',

    SHOW_CART: 'SHOW_CART',
    HIDE_CART: 'HIDE_CART',

    TOGGLE_OVERLAY: 'TOGGLE_OVERLAY',
    OVERLAY_CLICK: 'OVERLAY_CLICK',

    EXPAND_PRODUCT: 'EXPAND_PRODUCT',
    EXPAND_PRODUCT_RESPONSE: 'EXPAND_PRODUCT_RESPONSE',
    EXPAND_PRODUCT_ERROR: 'EXPAND_PRODUCT_ERROR'

};

export var events = {
    CHANGE: 'CHANGE'
}

