<?php

/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
if ( getenv('APPLICATION_ENV')  == 'development') {

    $appConfig = array(
        'modules' => array(
            'Application',
            'Account',
            'Catalog',
            'Admin',
            'Provider',
            'ZendDeveloperTools',
            'BjyProfiler',
            'ZFTool',
            'Sales',
            'Payment',
        ),
        'module_listener_options' => array(
            'module_paths' => array(
                './module',
                './vendor',
            ),
            'config_glob_paths' => array(
                'config/autoload/{,*.}{global,local}.php',
            ),
        ),
    );
} else {

    $appConfig = array(
        'modules' => array(
            'Application',
            'Catalog',
            'Account',
            'Admin',
            'Provider',
            'Sales',
            'Payment',
        ),
        'module_listener_options' => array(
            'module_paths' => array(
                './module',
                './vendor',
            ),
            'config_glob_paths' => array(
                'config/autoload/{,*.}{global,pro}.php',
            ),
        ),
    );
}

return $appConfig;


