<aside id="sidebar_left" class="nano nano-primary">
    <div class="nano-content">

        <!-- sidebar menu -->
        <ul class="nav sidebar-menu">

            <li class="sidebar-label pt20">Menu</li>
            <li>
                        <a href="#">
                            <span class="glyphicons glyphicons-charts"></span> Dashboard </a>
                    </li>
            <li>
                <a class="accordion-toggle " href="#">
                    <span class="glyphicons glyphicons-shopping_cart"></span>
                    <span class="sidebar-title">Catalogo</span>
                    <span class="caret"></span>
                </a>
                <ul class="nav sub-nav">
                    
                    <li class="">
                        <a href="<?php echo $this->url('admin', array('controller' => 'product', 'action' => 'list')); ?>">
                            <span class="glyphicons glyphicons-tags"></span> Productos </a>
                    </li>
                    <li class="">
                        <a href="<?php echo $this->url('admin', array('controller' => 'category', 'action' => 'list')); ?>">
                            <span class="glyphicons glyphicons-tags"></span> Categorias </a>
                    </li>
                    <li class="">
                        <a href="<?php echo $this->url('admin', array('controller' => 'category', 'action' => 'list')); ?>">
                            <span class="glyphicons glyphicons-tags"></span> Category </a>
                    </li>
<!--                    <li>
                        <a href="#">
                            <span class="glyphicons glyphicons-coins"></span> Orders </a>
                    </li>
                    <li >
                        <a href="#">
                            <span class="glyphicons glyphicons-user_add"></span> Customers </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="glyphicons glyphicons-keys"></span> Store Settings </a>
                    </li>-->
                </ul>
            </li>
            <li>
                <a class="accordion-toggle  " href="#">
                    <span class="glyphicons glyphicons-briefcase"></span>
                    <span class="sidebar-title">Provedores</span>
                    <span class="caret"></span>
                </a>
                <ul class="nav sub-nav">
                   
                    <li >
                        <a href="<?php echo $this->url('admin', array('controller' => 'provider', 'action' => 'list')); ?>">
                            <span class="glyphicons glyphicons-building"></span> Compañias</a>
                    </li>

                </ul>
            </li>
            <li>
                <a class="accordion-toggle  " href="#">
                    <span class="glyphicons glyphicons-briefcase"></span>
                    <span class="sidebar-title">Sales</span>
                    <span class="caret"></span>
                </a>
                <ul class="nav sub-nav">
                   
                 
                    <li >
                        <a href="<?php echo $this->url('admin', array('controller' => 'customer', 'action' => 'list')); ?>">
                            <span class="glyphicons glyphicons-building"></span> Clientes<span class="label label-xs bg-primary">New</span>
                        </a>
                    </li>
                    <li >
                        <a href="<?php echo $this->url('admin', array('controller' => 'seller', 'action' => 'list')); ?>">
                            <span class="glyphicons glyphicons-building"></span> Vendedores<span class="label label-xs bg-primary">New</span>
                        </a>
                    </li>
                  
                       <li >
                        <a href="<?php echo $this->url('admin', array('controller' => 'Order', 'action' => 'list')); ?>">
                            <span class="glyphicons glyphicons-building"></span> Ordenes<span class="label label-xs bg-primary">New</span>
                        </a>
                    </li>
                      <li >
                        <a href="#">
                            <span class="glyphicons glyphicons-building"></span> Pagos
                        </a>
                    </li>

                </ul>
            </li>
            <li>
                <a class="accordion-toggle  " href="#">
                    <span class="glyphicons glyphicons-briefcase"></span>
                    <span class="sidebar-title">Marketing</span>
                    <span class="caret"></span>
                </a>
                <ul class="nav sub-nav">
                   
                    <li >
                        <a href="#">
                            <span class="glyphicons glyphicons-building"></span> Mail - Newslatter</a>
                    </li>

                </ul>
            </li>
            <li>
                <a class="accordion-toggle  " href="#">
                    <span class="glyphicons glyphicons-briefcase"></span>
                    <span class="sidebar-title">System</span>
                    <span class="caret"></span>
                </a>
                <ul class="nav sub-nav">
                   
                    <li >
                        <a href="#">
                            <span class="glyphicons glyphicons-building"></span>Settings</a>
                    </li>

                </ul>
            </li>
            <li>
                <a class="accordion-toggle  " href="#">
                    <span class="glyphicons glyphicons-briefcase"></span>
                    <span class="sidebar-title">Reports</span>
                    <span class="caret"></span>
                </a>
                <ul class="nav sub-nav">
                   
                    <li >
                        <a href="#">Sales</a>
                    </li>
                    <li >
                        <a href="#">Products</a>
                    </li>
                    <li >
                        <a href="#">Customers</a>
                    </li>

                </ul>
            </li>
            <!-- sidebar bullets -->    
        </ul>
        <div class="sidebar-toggle-mini">
            <a href="#">
                <span class="fa fa-sign-out"></span>
            </a>
        </div>
    </div>
</aside>
