<aside id="sidebar_left" class="nano nano-primary">
    <div class="nano-content">

        <!-- sidebar menu -->
        <ul class="nav sidebar-menu">

            <li class="sidebar-label pt20">Menu</li>
            <li>
                <a class="accordion-toggle menu-open" href="#">
                    <span class="glyphicons glyphicons-shopping_cart"></span>
                    <span class="sidebar-title">Catalogo</span>
                    <span class="caret"></span>
                </a>
                <ul class="nav sub-nav">
                    <li>
                        <a href="#">
                            <span class="glyphicons glyphicons-shopping_cart"></span> Dashboard </a>
                    </li>
                    <li class="active">
                        <a href="<?php echo $this->url('admin', array('controller' => 'product', 'action' => 'list')); ?>">
                            <span class="glyphicons glyphicons-tags"></span> Products <span class="label label-xs bg-primary">New</span></a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="glyphicons glyphicons-coins"></span> Orders </a>
                    </li>
                    <li >
                        <a href="#">
                            <span class="glyphicons glyphicons-user_add"></span> Customers </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="glyphicons glyphicons-keys"></span> Store Settings </a>
                    </li>
                </ul>
            </li>
            <!-- sidebar bullets -->    
        </ul>
        <div class="sidebar-toggle-mini">
            <a href="#">
                <span class="fa fa-sign-out"></span>
            </a>
        </div>
    </div>
</aside>