<?php echo $this->doctype(); ?>

<html lang="es">
    <!-- Meta, title, CSS, favicons, etc. -->
    <?php echo $this->partial('layout/admin_head'); ?>

    <body class="ecommerce-page">

        <!-- Start: Theme Preview Pane -->

        <!-- Start: Main -->
        <div id="main">

            <!-- Start: Header -->
            <?php echo $this->partial('layout/admin_header'); ?>
            <!-- End: Header -->

            <!-- Start: Sidebar -->
            <?php echo $this->partial('layout/admin_sidebar'); ?>

            <!-- Start: Content-Wrapper -->
            <section id="content_wrapper" >
                <div class="theme-primary">
                <!-- Begin: Content -->
                <?php echo $this->content; ?>
                <!-- End: Content -->
                </div>
            </section>

        </div>
        <!-- End: Main -->

        <!-- BEGIN: PAGE SCRIPTS -->

        <!-- jQuery -->
        <script type="text/javascript" src="<?php echo $this->basePath('vendor') ?>/jquery/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('vendor') ?>/jquery/jquery_ui/jquery-ui.min.js"></script>

        <!-- Bootstrap -->
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/bootstrap/bootstrap.min.js"></script>
        
        <!-- Required -->
        <?php echo $this->headScript()
           // ->prependFile($this->basePath('assets_admin').'/js/utility/utility.js')
        ; ?>

        <!-- Theme Javascript-->
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/utility/utility.js"></script> 
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/main.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets_admin') ?>/js/demo.js"></script>
        <script type="text/javascript">
            jQuery(document).ready(function () {

                "use strict";

                // Init Theme Core    
                Core.init();

                // Init Theme Core    
                //Demo.init();

            });
        </script>
        <?php echo $this->inlineScript() ?>
        <!-- END: PAGE SCRIPTS -->

    </body>

</html>
