
<head>
        <!-- Meta -->
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no')
            ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
        ?>
     
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="keywords" content="MediaCenter, Template, eCommerce">
        <meta name="robots" content="all">

         <?php echo $this->headTitle($this->translate('.:: Lakari Home ::.'))->setAutoEscape(false) ?>

        <!-- Bootstrap Core CSS -->
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/bootstrap.min.css">

        <!-- Customizable CSS -->
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/reset.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/main.css">
        <!--link rel="stylesheet" href="<?php echo $this->basePath().'/assets/css/green.css'?>"-->
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/owl.carousel.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/owl.transitions.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/lightbox.css" >
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/animate.min.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/rateit.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/bootstrap-select.min.css">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/header.css"> 

        <!-- Icons/Glyphs -->
        <link rel="stylesheet" href="<?php echo $this->basePath('assets') ?>/css/font-awesome.min.css">

        <!-- Fonts --> 
        <!--link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,700' rel='stylesheet' type='text/css'-->
        <link href='<?php echo $this->basePath('assets') ?>/fonts/Champagne-Limousines-Bold/champagne-limousines-bold.css' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

        <!-- Favicon -->
        <link rel="shortcut icon" href="<?php echo $this->basePath('assets') ?>/images/favicon.ico">

        <!-- HTML5 elements and media queries Support for IE8 : HTML5 shim and Respond.js -->
        <!--[if lt IE 9]>
                <script src="<?php echo $this->basePath('assets') ?>/js/html5shiv.js"></script>
                <script src="<?php echo $this->basePath('assets') ?>/js/respond.min.js"></script>
        <![endif]-->

    </head>
