 <!-- ============================================== HEADER ============================================== -->

<nav class="navbar top-navbar navbar-fixed-top" role="navigation">

  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="button-navbar-toggle navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar top-bar-icon"></span>
        <span class="icon-bar middle-bar"></span>
        <span class="icon-bar bottom-bar"></span>
      </button>

        <div class="lakari-brand navbar-brand">
            <div class="lakari-logo">
                <img class="img-responsive" src="<?php echo $this->basePath('assets/images') ?>/lakari-logo.png" alt="Lakari">
            </div>
        </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
     
      <ul class="nav navbar-nav navbar-left">

        <li><a class="navbar-link" href="#">Muebles</a></li>
        <li><a class="navbar-link" href="#">Griferias</a></li>
        <li><a class="navbar-link" href="#">Iluminación</a></li>
        <li><a class="navbar-link" href="#">Utensilios</a></li>
        <li><a class="navbar-link" href="#">Servicios</a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
            <form class="navbar-search navbar-form navbar-right" role="search">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-search fa-fw"></i>
                    </span>
                    <input class="form-control" type="password" placeholder="Busqueda">
                </div>
            </form>
        </li>
<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-lg"></i><span class="caret"></span><label class="visible-xs navbar-link">  Cuenta</label></a>
          <ul class="dropdown-menu">
            <li><a href="#">Perfil</a></li>
            <li><a href="#">Idioma</a></li>
            <li><a href="#">Favoritos</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Salir</a></li>
          </ul>
        </li>
        <li>
            <div class="navbar-form navbar-right">
                <button type="button" class="icon lnk btn"> 
                    <i class="fa fa-shopping-cart fa-lg"></i> 
                    <span class="visible-xs navbar-link "> Carrito de Compras</span>
                </button>
            <div>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--
	<div id="cd-shadow-layer"></div>

	<div id="cd-cart">
		<h2>Cart</h2>
		<ul class="cd-cart-items">
			<li>
				<span class="cd-qty">1x</span> Product Name
				<div class="cd-price">$9.99</div>
				<a href="#0" class="cd-item-remove cd-img-replace">Remove</a>
			</li>

			<li>
				<span class="cd-qty">2x</span> Product Name
				<div class="cd-price">$19.98</div>
				<a href="#0" class="cd-item-remove cd-img-replace">Remove</a>
			</li>

			<li>
				<span class="cd-qty">1x</span> Product Name
				<div class="cd-price">$9.99</div>
				<a href="#0" class="cd-item-remove cd-img-replace">Remove</a>
			</li>
		</ul> 

		<div class="cd-cart-total">
			<p>Total <span>$39.96</span></p>
		</div> 

		<a href="#0" class="checkout-btn">Checkout</a>
		
		<p class="cd-go-to-cart"><a href="#0">Go to cart page</a></p>
	</div> 
-->

<!-- ============================================== HEADER : END ============================================== -->
