
<div class="modal signUpContent fade" id="ModalLogin" tabindex="-1" role="dialog">
    <div class="modal-dialog ">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
                <h3 class="modal-title-site text-center"> Ingresar a Lakari </h3>
            </div>
            <div class="modal-body">
                
                <div class="form-group login-username">
                    <div>
                        <input name="log" id="login-user" class="form-control input" size="20" placeholder="Usuario" type="text">
                    </div>
                </div>
                <div class="form-group login-password">
                    <div>
                        <input name="Password" id="login-password" class="form-control input" size="20" placeholder="Contraseña" type="password">
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <div class="checkbox login-remember">
                            <!--label>
                              <input name="rememberme" value="forever" checked="checked" type="checkbox">
                              Recordarme </label-->
                        </div>
                    </div>
                </div>
                <div>
                    <div>
                        <a href="index-login.php">
                            <input name="submit" class="btn  btn-block btn-lg btn-primary" value="Ingresar" type="submit">
                        </a>
                    </div>
                </div>
                <!--userForm--> 
            
            </div>
            <div class="modal-footer">
                <p class="text-center"> ¿No tienes cuenta? <a data-toggle="modal" data-dismiss="modal" href="#ModalSignup"> Regístrate. </a> <br>
                    <a href="password.php"> ¿Olvidó contraseña? </a> </p>
            </div>
        </div>
        <!-- /.modal-content --> 

    </div>
    <!-- /.modal-dialog --> 

</div>
<!-- /.Modal Login --> 

<!-- Modal Signup start -->
<div class="modal signUpContent fade" id="ModalSignup" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
                <h3 class="modal-title-site text-center"> Registrarse en Lakari </h3>
            </div>
            <div class="modal-body">
                <form action="<?php echo $this->url('account', array('controller' => 'register', 'action' => 'add')) ?>" method="post">
                <div class="control-group"> <a class="fb_button btn  btn-block btn-lg " href="#"> Vía Facebook </a> </div>
                <h5 style="padding:10px 0 10px 0;" class="text-center"> O </h5>
                <div class="form-group reg-username">
                    <div>
                         <?php echo $this->formInput($this->registerForm->get('firstname')); ?>
                    </div>
                </div>
                <div class="form-group reg-username">
                    <div>
                          <?php echo $this->formInput($this->registerForm->get('lastname')); ?>
                    </div>
                </div>
                <div class="form-group reg-email">
                    <div>
                        <?php echo $this->formInput($this->registerForm->get('email')); ?>
                     
                    </div>
                </div>
                <div class="form-group reg-password">
                    <div>
                         <?php echo $this->formInput($this->registerForm->get('password')); ?>
                    </div>
                </div>
    
                <div class="form-group">
                    <div>
                        <div class="checkbox login-remember">
                            <label>
                                 <?php echo $this->formInput($this->registerForm->get('rememberme')); ?>
                                
                                Recordarme 
                            </label>
                        </div>
                    </div>
                </div>
                <div>
                    <div>
                        <a href="registro.php">
                            <input name="submit" class="btn btn-block btn-lg btn-primary" value="Registrar" type="submit">
                        </a>
                    </div>
                </div>
                <?php echo $this->formInput($this->registerForm->get('csrf')); ?>
              </form>
            </div>
            <div class="modal-footer">
                <p class="text-center"> ¿Ya eres miembro? <a data-toggle="modal" data-dismiss="modal" href="#ModalLogin"> Ingresar </a> </p>
            </div>
        </div>

    </div>

</div>
<!-- /.ModalSignup End --> 
 


<!-- ============================================== HEADER ============================================== -->

<header class='header'>
  <nav class='navbar navbar-primary'>
    <div class='navbar-container'>
      <div class='navbar-wrapper'>
        <div class='logo-wrapper'>
            <div class='logo-container'>
              <a><img class="icon-grovemade-logo-type" src='http://placehold.it/150x45' /></a>
            </div>
        </div>
        <div class='primary-links'>
          <ul class='main-links'>
            <li><a href='#'>Contactos</a></li>
            <li><a href='#'>Vende en Lákari</a></li>
<li><a class="navbar-link" href="#" data-toggle="modal" data-target="#ModalLogin">Login</a></li>
          </ul>
          <ul class='extra-links'>
            <li class='nav-dropdown nav-dropdown-toggle'>
                <a class='' href='#'>Productos
                    <i class="fa fa-caret-down"></i>
                </a>
                  <ul class='nav-dropdown-menu'>
                      <li>
                        <a href='#'>
                          <div class='image-nav'>
                            <img class="img-responsive" src='http://placehold.it/120x120' />
                          </div>
                          <h3 class='extra-nav-title'>Muebles</h3>
                        </a>
                    </li>
                      <li>
                        <a href='#'>
                           <div class='image-nav'>
                             <img class="img-responsive" src='http://placehold.it/120x120' />
                          </div>
                          <h3 class='extra-nav-title'>Griferias</h3>
                        </a>
                    </li>
                      <li>
                        <a href='#'>  
                          <div class='image-nav'>
                          <img class="img-responsive" src='http://placehold.it/120x120' /></div>
                          <h3 class='extra-nav-title'>Iluminación</h3>
                        </a>
                    </li>
                      <li>
                        <a href='#'>  
                          <div class='image-nav'>
                          <img class="img-responsive" src='http://placehold.it/120x120' /></div>
                          <h3 class='extra-nav-title'>Utensilios</h3>
                        </a>
                    </li>
                  </ul>
            </li>
            <li class='nav-dropdown nav-dropdown-toggle'>
                <a class='' href='#'>Inspiración
                    <i class="fa fa-caret-down"></i>
                </a>
                <ul class='nav-dropdown-menu'>
                    <li>
                      <a href='#'>
                        <div class='image-nav'>
                             <img class="img-responsive" src='http://placehold.it/120x120' />
                          </div>
                          <h3 class='extra-nav-title'>Salas</h3>
                      </a>
                  </li>
                    <li>
                      <a href='#'>
                         <div class='image-nav'>
                             <img class="img-responsive" src='http://placehold.it/120x120' />
                          </div>
                          <h3 class='extra-nav-title'>Cuartos</h3>
                      </a>
                  </li>
                    <li>
                      <a href='#'>
                         <div class='image-nav'>
                             <img class="img-responsive" src='http://placehold.it/120x120' />
                          </div>
                          <h3 class='extra-nav-title'>Baños</h3>
                      </a>
                  </li>
                    <li>
                      <a href='#'>
                         <div class='image-nav'>
                             <img class="img-responsive" src='http://placehold.it/120x120' />
                          </div>
                          <h3 class='extra-nav-title'>Cocinas</h3>
                      </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href='#'>Servicios</a>
            </li>
          </ul>
        </div>       
        <ul class='secondary-links'>
          <li class='mobile-toggle'>     
              <div class='mobile-menu-icon'>
                <span></span>
                <span></span>
                <span></span>
              </div>        
          </li>
          <li><a><i class="fa fa-facebook-official"></i></a></li>
          <li><a><i class="fa fa-instagram"></i></a></li>
          <li><a><i class="fa fa-twitter"></i></a></li>
          <li><a><i class="fa fa-pinterest-p"></i></a></li>
          <li id='cd-cart-trigger'><a><i class="fa fa-shopping-cart"></i></a></li>
        </ul>   

      </div>
        <!-- Cart -->
        <div id='cd-cart'></div>
        <!-- Cart -->
    </div>
  </nav>
</header>
