<div class="modal signUpContent fade" id="ModalLogin" tabindex="-1" role="dialog">
    <div class="modal-dialog ">
        <div class="modal-content">
            <form action="<?php echo $this->url('account', array('controller' => 'login')) ?>" method="post">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
                <h3 class="modal-title-site text-center"> Ingresar a LakariHome </h3>
            </div>
            <div class="modal-body">
                
                <div class="form-group login-username">
                    <div>
                        <?php echo $this->formInput($this->registerForm->get('email')); ?>
                    </div>
                </div>
                <div class="form-group login-password">
                    <div>
                        <?php echo $this->formInput($this->registerForm->get('password')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <div class="checkbox login-remember">
                           <label>
                                 <?php echo $this->formInput($this->registerForm->get('rememberme')); ?>
                                
                                Recordarme 
                            </label>
                        </div>
                    </div>
                </div>
                <div>
                    <div>
                       <input name="submit" class="btn  btn-block btn-lg btn-primary" value="Ingresar" type="submit">
                    </div>
                </div>
                <!--userForm--> 
            
            </div>
                 <?php echo $this->formInput($this->registerForm->get('csrf')); ?>
            <div class="modal-footer">
                <p class="text-center"> ¿No tienes cuenta? <a data-toggle="modal" data-dismiss="modal" href="#ModalSignup"> Regístrate. </a> <br>
                    <a href="password.php"> ¿Olvidó contraseña? </a> </p>
            </div>
                </form>
        </div>
        <!-- /.modal-content --> 

    </div>
    <!-- /.modal-dialog --> 

</div>
<!-- /.Modal Login -->  

<!-- Modal Signup start -->
<div class="modal signUpContent fade" id="ModalSignup" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
                <h3 class="modal-title-site text-center"> Registrarse en Lakari </h3>
            </div>
            <div class="modal-body">
                <form action="<?php echo $this->url('account', array('controller' => 'register', 'action' => 'add')) ?>" method="post">
                <div class="control-group"> <a class="fb_button btn  btn-block btn-lg " href="#"> Vía Facebook </a> </div>
                <h5 style="padding:10px 0 10px 0;" class="text-center"> O </h5>
                <div class="form-group reg-username">
                    <div>
                         <?php echo $this->formInput($this->registerForm->get('firstname')); ?>
                    </div>
                </div>
                <div class="form-group reg-username">
                    <div>
                          <?php echo $this->formInput($this->registerForm->get('lastname')); ?>
                    </div>
                </div>
                <div class="form-group reg-email">
                    <div>
                        <?php echo $this->formInput($this->registerForm->get('email')); ?>
                     
                    </div>
                </div>
                <div class="form-group reg-password">
                    <div>
                         <?php echo $this->formInput($this->registerForm->get('password')); ?>
                    </div>
                </div>
    
                <div class="form-group">
                    <div>
                        <div class="checkbox login-remember">
                            <label>
                                 <?php echo $this->formInput($this->registerForm->get('rememberme')); ?>
                                
                                Recordarme 
                            </label>
                        </div>
                    </div>
                </div>
                <div>
                    <div>
                        <a href="registro.php">
                            <input name="submit" class="btn btn-block btn-lg btn-primary" value="Registrar" type="submit">
                        </a>
                    </div>
                </div>
                <?php echo $this->formInput($this->registerForm->get('csrf')); ?>
              </form>
            </div>
            <div class="modal-footer">
                <p class="text-center"> ¿Ya eres miembro? <a data-toggle="modal" data-dismiss="modal" href="#ModalLogin"> Ingresar </a> </p>
            </div>
        </div>

    </div>

</div>
<!-- /.ModalSignup End --> 
 


<!-- ============================================== HEADER ============================================== -->

<nav class="navbar top-navbar navbar-fixed-top" role="navigation">

  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="button-navbar-toggle navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar top-bar-icon"></span>
        <span class="icon-bar middle-bar"></span>
        <span class="icon-bar bottom-bar"></span>
      </button>

        <div class="lakari-brand navbar-brand">
            <div class="lakari-logo">
                <img class="img-responsive" src="<?php echo $this->basePath('assets/images') ?>/lakari-logo.png" alt="Lakari">
            </div>
        </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
     
      <ul class="nav navbar-nav navbar-left">

        <li><a class="navbar-link" href="#">Muebles</a></li>
        <li><a class="navbar-link" href="#">Griferias</a></li>
        <li><a class="navbar-link" href="#">Iluminación</a></li>
        <li><a class="navbar-link" href="#">Utensilios</a></li>
        <li><a class="navbar-link" href="#">Servicios</a></li>
        <li><a class="navbar-link" href="#" data-toggle="modal" data-target="#ModalLogin">Login</a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
            <form class="navbar-search navbar-form navbar-right" role="search">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-search fa-fw"></i>
                    </span>
                    <input class="form-control" type="password" placeholder="Busqueda">
                </div>
            </form>
        </li>
<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-lg"></i><span class="caret"></span><label class="visible-xs navbar-link">  Cuenta</label></a>
          <ul class="dropdown-menu">
            <li><a href="#">Perfil</a></li>
            <li><a href="#">Idioma</a></li>
            <li><a href="#">Favoritos</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Salir</a></li>
          </ul>
        </li>
        <li>
            <div class="navbar-form navbar-right">
                <div id='cd-cart-trigger'> </div>           
            </div>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- ============================================== HEADER : END ============================================== -->

