<?php
$this->headlink()->prependStylesheet($this->basePath() . '/vendor/plugins/select2/css/core.css')
        ->prependStylesheet($this->basePath() . '/css/bundle.min.css');
?>
<!-- Start: Topbar -->
<header id="topbar" class="ph10">
    <div class="topbar-left">
        <ul class="nav nav-list nav-list-topbar pull-left">
                       
            <li class="active">
                <a href="<?php echo $this->url('admin', array('controller' => 'seller', 'action' => 'list')); ?>">List</a>
            </li>

        </ul>
    </div>
</header>
<!-- End: Topbar -->

<!-- Begin: Content -->
<section id="content" class="table-layout animated fadeIn">
    <!-- end: .tray-center -->
</section>
<!-- End: Content -->
<?php
$this->headScript()
   //     ->prependFile($this->basePath() . '/vendor/plugins/fileupload/fileupload.js')
  //      ->prependFile($this->basePath() . '/vendor/plugins/tagsinput/tagsinput.min.js')
        ->prependFile($this->basePath() . '/vendor/plugins/select2/select2.min.js')
  //      ->prependFile($this->basePath() . '/assets_admin/js/bootstrap/holder.min.js')
        ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/advanced/steps/jquery.steps.js')
        ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/jquery.validate.min.js')
// ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/additional-methods.min.js')
;
$urlAjax = $this->url('admin', array('controller' => 'order'));
$products = $this->products;
$customers = $this->customers;

$this->inlineScript()->captureStart();
 echo <<<JS

   var URL_AJAX = '{$urlAjax}';
   var PRODUCTS = '{$products}';
   var CUSTOMERS = '{$customers}';

   jQuery(document).ready(function() { 

// Form Wizard 
    var form = $("#form-wizard");

    form.validate({
        /* @validation states + elements 
          ------------------------------------------- */
         errorClass: "state-error",
         validClass: "state-success",
         errorElement: "em",
         ignore: false,
         /* @validation rules 
          ------------------------------------------ */
           rules: {
           
            customer_id: {
                    required: true
            },                   
        },
        messages:{
            customer_id: {
                    required: 'Campo Obligatorio'
            },    
        },
    });

//    form.children(".wizard").steps({
//      headerTag: ".wizard-section-title",
//      bodyTag: ".wizard-section",
//      //transitionEffect: "slideLeft",
//      autoFocus: true
//    });

    // Demo Wizard Functionality
    var formWizard = $('.wizard');
    var formSteps = formWizard.find('.steps');

     $("#multiselect").select2({
              placeholder: "Select User",
               allowClear: true,
               style: "bg-primary light"
            });
  });
    
JS;
$this->inlineScript()->captureEnd();
$this->inlineScript()->appendFile($this->basePath('/assets_admin/js/bundle.min.js'));

