<?php
$this->headlink()
        
      //  ->prependStylesheet($this->basePath() . '/vendor/plugins/select2/css/core.css');
?>
<!-- Start: Topbar -->
<header id="topbar" class="ph10">
    <div class="topbar-left">
        <ul class="nav nav-list nav-list-topbar pull-left">
                       
            <li class="active">
                <a href="<?php echo $this->url('admin', array('controller' => 'customer', 'action' => 'list')); ?>"></a>
            </li>

        </ul>
    </div>
    <!--    <div class="topbar-right hidden-xs hidden-sm">
          
            <a href="ecommerce_products.html" class="btn btn-default btn-sm light fw600 ml10">
                <span class="fa fa-plus pr5"></span> Add Product</a>
            <a href="ecommerce_customers.html" class="btn btn-default btn-sm light fw600 ml10">
                <span class="fa fa-user pr5"></span> Add Company</a>
        </div>-->
</header>
<!-- End: Topbar -->

<!-- Begin: Content -->
<section id="content" class="table-layout animated fadeIn">

    <!-- begin: .tray-center -->
    <div class="tray tray-center">
       
        <!-- create new order panel -->
        <div class="panel mb25 mt5">
            <div class="panel-heading">
                <span class="panel-title hidden-xs"> Agregar Nuevo Cliente</span>
                <ul class="nav panel-tabs-border panel-tabs">
                    <li class="active">
                        <a href="#tab1_1" data-toggle="tab">General</a>
                    </li>
                    <li>
                        <a href="#tab1_2" data-toggle="tab">Configuración</a>
                    </li>
                    <!--li>
                        <a href="#tab1_3" data-toggle="tab">Dirección</a>
                    </li-->
                </ul>
            </div>
            <div class="panel-body p20 pb10 form-horizontal">
                <form id="form"  action="<?php echo $this->basePath($this->form->getAttribute('action')); ?>" method="post" >   
                     <?php echo $this->formInput($this->form->get('customer_id')); ?>
                    <div class="tab-content pn br-n admin-form">
                        <div id="tab1_1" class="tab-pane active">

                            <div class="section row mbn">
                               
                                <div class="col-md-12 ">
                                    <div class="section row  form-group">
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="firstname">Nombre <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="firstname" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->form->get('firstname')); ?>
                                                    <label for="firstname" class="field-icon"><i class="fa fa-user"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->form->get('firstname')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="lastname">Apellido <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="lastname" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->form->get('lastname')); ?>
                                                    <label for="lastname" class="field-icon"><i class="fa fa-barcode"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->form->get('lastname')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                     <div class="section row  form-group">
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="telephone">Telephone <span class="text-danger">*</span></label>
                                            <div class="col-md-4">
                                                <label for="telephone" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->form->get('telephone')); ?>
                                                    <label for="telephone" class="field-icon"><i class="fa fa-user"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->form->get('telephone')) ?> 
                                                </div>
                                            </div>

                                            <label class="col-md-1 control-label" for="movil">Celular <span class="text-danger">*</span></label>
                                            <div class="col-md-4">
                                                <label for="movil" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->form->get('movil')); ?>
                                                    <label for="movil" class="field-icon"><i class="fa fa-barcode"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->form->get('movil')) ?> 
                                                </div>
                                            </div>
                                           
                                        </div>
                                        <div class="col-xs-6">
                                             <label class="col-md-3 control-label" for="fax">Fax <span class="text-danger">*</span></label>
                                            <div class="col-md-4">
                                                <label for="fax" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->form->get('fax')); ?>
                                                    <label for="fax" class="field-icon"><i class="fa fa-barcode"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->form->get('fax')) ?> 
                                                </div>
                                            </div>
                                             
                                             <div class="col-md-4">
                                                 <div class="checkbox-custom mb5">
                                                     <input type="checkbox" checked="" id="newsletter">
                                                     <?php //echo $this->formInput($this->form->get('newsletter')); ?>  
                                                     <label for="newsletter">Newsletter</label>
                                                 </div>      
                                             </div>
                                        </div>
                                    </div>
                                    <div class="section row  form-group">
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="email">Email <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="email" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->form->get('email')); ?>
                                                    <label for="email" class="field-icon"><i class="fa fa-user"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->form->get('email')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="confirmEmail">Confirmar Email <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="confirmEmail" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->form->get('confirmEmail')); ?>
                                                    <label for="confirmEmail" class="field-icon"><i class="fa fa-barcode"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->form->get('confirmEmail')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                   
                                    <div class="section row  form-group"> 
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="password">Password <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="password" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->form->get('password')); ?>
                                                    <label for="password" class="field-icon"><i class="fa fa-barcode"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->form->get('password')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="confirmPassword">Confirmar Password<span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="confirmPassword" class="field prepend-icon">                                       
                                                    <?php echo $this->formInput($this->form->get('confirmPassword')); ?>
                                                    <label for="confirmPassword" class="field-icon"><i class="fa fa-barcode"></i>
                                                    </label>
                                                </label> 
                                                <div class="help-block">
                                                    <?php echo $this->formelementerrors($this->form->get('confirmPassword')) ?> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                   
                                </div>
                                
                            </div>
                            <!-- end section row -->

                        </div>
                        
                         <hr class="short alt mtn">
                        <div class="panel-footer text-right mt5">
                            <button class="btn btn-primary text-right"> Crear Cliente </button>
                        </div>
                    </div>
                    
                </form>
            </div>
        </div>

        <!-- recent orders table -->
       

    </div>
    <!-- end: .tray-center -->

    <!-- begin: .tray-right -->

    <!-- end: .tray-right -->

</section>
<!-- End: Content -->
<?php
$this->headScript()
   //     ->prependFile($this->basePath() . '/vendor/plugins/fileupload/fileupload.js')
  //      ->prependFile($this->basePath() . '/vendor/plugins/tagsinput/tagsinput.min.js')
  //      ->prependFile($this->basePath() . '/vendor/plugins/select2/select2.min.js')
  //      ->prependFile($this->basePath() . '/assets_admin/js/bootstrap/holder.min.js')
 //       ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/advanced/steps/jquery.steps.js')
        ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/jquery.validate.min.js')
// ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/additional-methods.min.js')
;
$this->inlineScript()->captureStart();
 echo <<<JS
   
    
JS;
$this->inlineScript()->captureEnd();
