<?php
$this->headlink()
        
        ->prependStylesheet($this->basePath() . '/vendor/plugins/select2/css/core.css');
?>
<!-----------------------------------
            Start: Topbar 
-------------------------------------->
<header id="topbar" class="ph10">
    <div class="topbar-left">
        <ul class="nav nav-list nav-list-topbar pull-left">
            <li >
                <a href="#">Dashboard</a>
            </li>
            <li class="active">
                <a href="<?php echo $this->url('admin', array('controller' => 'category', 'action' => 'list')); ?>">Category</a>
            </li>
            <li>
                <a href="#">Orders</a>
            </li>
            <li>
                <a href="#">Customers</a>
            </li>
            <li>
                <a href="#">Settings</a>
            </li>
        </ul>
    </div>
    <div class="topbar-right">  
        <a href="<?php echo $this->url('admin', array('controller' => 'category', 'action' => 'add')); ?>" class="btn btn-primary btn-sm light fw600 ml10"><span class="fa fa-plus pr5"></span> Add Product</a>
    </div>
</header>
<!--------------------------------- 
            End: Topbar
----------------------------------->

<!-----------------------------------
    FORMULARIO PARA AGREGAR CATEGORIA
-------------------------------------->
    <section id="content" class="table-layout animated fadeIn">
        <div class="tray tray-center">
         <?php if($this->save == 1) {
                        $message = "Provedor <strong> Creado </strong> satisfactoriamente";
                        echo $this->alert('succes',$message);
                    }
                ?>
            <div class="panel mb25 mt5">     <!--inicio cuadro general-->
                <div class="panel-heading">     <!--cuadro titulo-->
                    <span class="panel-title hidden-xs"> Agregar Nuevo Provedor</span>
                </div>


                <div class="panel-body p20 pb10 form-horizontal">       <!--cuadro formulario -->
                    <form id="form"  action="<?php echo $this->basePath($this->categoryForm->getAttribute('action')) ;?>" method="post" enctype="multipart/form-data">

                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">

                                <div class="section row mbn">
                                    <div class="col-md-2">
                                        <div class="fileupload fileupload-new admin-form" data-provides="fileupload">
                                            <div class="fileupload-new thumbnail" style="">
                                                <img data-src="holder.js/200x100/text:logo" src="" />
                                            </div>
                                            <div class="fileupload-preview fileupload-exists thumbnail" style=""></div>
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <span class="button btn-system btn-file btn-block">
                                                        <span class="fileupload-new">Select</span>
                                                        <span class="fileupload-exists">Change</span>
                                                        <?php echo $this->formFile($this->categoryForm->get('logo')); ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                               

                                <div class="col-md-10 ">
                                    <div class="section row  form-group">
  <!--                                      <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="company">Parent_id: <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="company" class="field prepend-icon">                                       
                                                    <?php //$parent_id = $this->categoryForm->get('parent_id'); ?>
                                                    <?php //echo $this->formInput($parent_id); ?>
                                            </div>
                                        </div>-->
                                      <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="company">Categoria: <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="company" class="field prepend-icon">                                       
                                                    <?php $name = $this->categoryForm->get('name'); ?>
                                                    <?php echo $this->formInput($name); ?>
                                                    <label for="name" class="field-icon"><i class="fa fa-user"></i></label>
                                                    <div class="error"><?php echo $this->formelementerrors($name) ?>  </div>
                                                </label> 
                                            </div>
                                        </div>
                                        
                                         <div class="col-xs-6">
                                          <label class="col-lg-3 control-label" for="status">Status <span class="text-danger">*</span></label>
                                                <div class="col-md-9 "> 
                                                    <label class="field select">
                                                        <?php echo $this->formRow($this->categoryForm->get('status')) ?>
                                                        <i class="arrow double "></i>
                                                    </label>
                                                    <div class="help-block">
                                                        <?php echo $this->formelementerrors($this->categoryForm->get('status')) ?> 
                                                    </div>
                                                </div>
                                        </div>
                                        
                                    </div>
                                    
                                    <div class="section row  form-group">
                                        <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="company">Descripcion: <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label class="field prepend-icon">                                       
                                                    <?php echo $this->formTextarea($this->categoryForm->get('description')); ?>
                                                </label> 
                                            </div>
                                        </div>
                                        
                                        <div class="col-xs-6">
                                          <label class="col-lg-3 control-label" for="status">Sort Order <span class="text-danger">*</span></label>
                                                <div class="col-md-9 "> 
                                                    <label class="field select">
                                                        <?php echo $this->formInput($this->categoryForm->get('sort_order')) ?>
                                                        <i class="arrow double "></i>
                                                    </label>
                                                    <div class="help-block">
                                                        <?php echo $this->formelementerrors($this->categoryForm->get('sort_order')) ?> 
                                                    </div>
                                                </div>
                                        </div>
                                    </div>
                                    
                                   <div class="section row  form-group">
                                        <div class="col-xs-6">
                                          <label class="col-lg-3 control-label" for="column">Top <span class="text-danger">*</span></label>
                                                <div class="col-md-9 "> 
                                                        <?php echo $this->formRow($this->categoryForm->get('top')) ?>
                                                    <div class="help-block">
                                                        <?php echo $this->formelementerrors($this->categoryForm->get('top')) ?> 
                                                    </div>
                                                </div>
                                        </div>
                                       
<!--                                      <div class="col-xs-6">
                                            <label class="col-md-3 control-label" for="company">Category_id: <span class="text-danger">*</span></label>
                                            <div class="col-md-9">
                                                <label for="company" class="field prepend-icon">                                       
                                                    <?php //echo $this->formInput($this->categoryForm->get('category_id')); ?>
                                                </label> 
                                            </div>
                                        </div>-->
                                    </div>
                                        
                                </div>
                            </div>
                        </div>
                             <hr class="short alt mtn">
                        <div class="panel-footer text-right mt5">
                            <button type="submit" class="btn btn-primary text-right"> Crear Categoria </button>
                        </div>
                    </div>
                    </form>
                </div> <!--cierre formulario -->
                
                    


            </div> <!--cierre cuadro general -->
        </div>
    </section>
<!---------------------------------------
    VISTA TRAIDA DE LA BD
------------------------------------------>

<section class="table-layout" id="content">
    <div class="panel p">
        <div class="panel-body pn col-lg-10 col-lg-offset-1 col-md-10 col-lg-offset-1 col-sm-11">
            
            <table class="table admin-form theme-warning tc-checkbox-1 fs13">
                <thead>
                    <tr class="bg-light">
                        <th class="text-center">Select</th>
                        <th class="">Image</th>
                        <th class="">Title</th>
                        <th class="text-center">Top</th> 
                        <th class="text-center">Sort Order</th>
                        <th class=""></th>
                        <th class="text-right">Status</th>
                    </tr>
                </thead>
                
                <tbody>
                 <?php foreach ($this->category as $category) : ?>
                
             
                    <tr data-id="<?php echo $category->category_id;?>">
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <a href="" target="_blank"> 
                                <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets/images/category/5.jpg')?>">
                            </a>
                        </td>
                        <td class=""><?php echo $category->name;?></td>
                        <td class="text-center"><?php echo $category->top ;?></td>
                        <td class="text-center"><?php echo $category->sort_order;?></td>
                        <td class=""></td>
                        <td class="text-right">
                            <div class="btn-group text-right"><?php 
                                    $status = $category->status;
                                    switch($status){
                                        case 0: ?>
                                <button type="button" class="btn btn-danger br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="true">Inactive<span class="caret ml5"></span></button>
                                        <?php    break;
                                        case 1:?>
                                <button type="button" class="btn btn-success br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="true">Active<span class="caret ml5"></span></button>
                                         <?php break;      
                                    } ?>
                                    
                                
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="">Edit</a>
                                    </li>
                                    <li>
                                        <a class="btn-delete" href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                     <?php endforeach; ?> 
                    
                </tbody>
            </table>
        </div>
    </div>
</section>

    <?php
$this->inlineScript()->captureStart();
echo <<<JS
//<script type="text/javascript">
   jQuery('document').ready(function(){
       
       
       $('.btn-delete').click(function(e){
           e.preventDefault();
            var row = $(this).closest('tr');
            var id = row.data('id');
          bootbox.confirm("Are You Sure?!", function(e) {

                // e returns true if user clicks "accept"
                // false if "cancel" or dismiss icon are clicked
                if (e) {  
                  

                      $.ajax({
                            url: '../product/delete/'+id,
                            type: 'post',
                            data: 'id='+id,
                            dataType: 'json',
                            beforeSend: function() {

                                    },
                            complete: function() {

                            },
                            success: function(json) {
                                row.fadeOut();
                            },
                            error: function(xhr, ajaxOptions, thrownError) {
                                alert(thrownError + "-" + xhr.status );
                            }
                     });
               } else {
                   return;
               }
               
               
               
           })
        })
        
   })

//</script>

JS;
$this->inlineScript()->captureEnd();