<?php
$this->headlink()
        
        ->prependStylesheet($this->basePath() . '/vendor/plugins/select2/css/core.css');
?>
<!-- Start: Topbar -->
<header id="topbar" class="ph10">
    <div class="topbar-left">
        <ul class="nav nav-list nav-list-topbar pull-left">
            <li >
                <a href="#">Dashboard</a>
            </li>
            <li class="active">
                <a href="<?php echo $this->url('admin', array('controller' => 'category', 'action' => 'list')); ?>">Category</a>
            </li>
            <li>
                <a href="#">Orders</a>
            </li>
            <li>
                <a href="#">Customers</a>
            </li>
            <li>
                <a href="#">Settings</a>
            </li>
        </ul>
    </div>
    <div class="topbar-right">  
        <a href="<?php echo $this->url('admin', array('controller' => 'category', 'action' => 'add')); ?>" class="btn btn-primary btn-sm light fw600 ml10"><span class="fa fa-plus pr5"></span> Add Product</a>
    </div>
</header>
<!-- End: Topbar -->

<section class="table-layout" id="content">
    <div class="panel p">
        <div class="panel-body pn col-lg-10 col-lg-offset-1 col-md-10 col-lg-offset-1 col-sm-11">
            
            <table class="table admin-form theme-warning tc-checkbox-1 fs13">
                <thead>
                    <tr class="bg-light">
                        <th class="text-center">Select</th>
                        <th class="">Image</th>
                        <th class="">Title</th>
                        <th class="text-center">Top</th> 
                        <th class="text-center">Sort Order</th>
                        <th class=""></th>
                        <th class="text-right">Status</th>
                    </tr>
                </thead>
                
                <tbody>
                 <?php foreach ($this->category as $category) : ?>
                
             
                    <tr data-id="<?php echo $category->category_id;?>">
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <a href="" target="_blank"> 
                                <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets/images/category/5.jpg')?>">
                            </a>
                        </td>
                        <td class=""><?php echo $category->name;?></td>
                        <td class="text-center"><?php echo $category->top ;?></td>
                        <td class="text-center"><?php echo $category->sort_order;?></td>
                        <td class=""></td>
                        <td class="text-right">
                            <div class="btn-group text-right"><?php 
                                    $status = $category->status;
                                    switch($status){
                                        case 0: ?>
                                <button type="button" class="btn btn-danger br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="true">Inactive<span class="caret ml5"></span></button>
                                        <?php    break;
                                        case 1:?>
                                <button type="button" class="btn btn-success br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="true">Active<span class="caret ml5"></span></button>
                                         <?php break;      
                                    } ?>
                                    
                                
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="">Edit</a>
                                    </li>
                                    <li>
                                        <a class="btn-delete" href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                     <?php endforeach; ?> 
                    
                </tbody>
            </table>
        </div>
    </div>

</section>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
//<script type="text/javascript">
   jQuery('document').ready(function(){
       
       
       $('.btn-delete').click(function(e){
           e.preventDefault();
            var row = $(this).closest('tr');
            var id = row.data('id');
          bootbox.confirm("Are You Sure?!", function(e) {

                // e returns true if user clicks "accept"
                // false if "cancel" or dismiss icon are clicked
                if (e) {  
                  

                      $.ajax({
                            url: '../product/delete/'+id,
                            type: 'post',
                            data: 'id='+id,
                            dataType: 'json',
                            beforeSend: function() {

                                    },
                            complete: function() {

                            },
                            success: function(json) {
                                row.fadeOut();
                            },
                            error: function(xhr, ajaxOptions, thrownError) {
                                alert(thrownError + "-" + xhr.status );
                            }
                     });
               } else {
                   return;
               }
               
               
               
           })
        })
        
   })

//</script>

JS;
$this->inlineScript()->captureEnd();