<?php
$this->headlink()
        ->prependStylesheet($this->basePath() . '/vendor/plugins/dropzone/css/dropzone.css')
        ->prependStylesheet($this->basePath() . '/vendor/plugins/select2/css/core.css');
?>
<!-- Start: Topbar -->
<header id="topbar" class="ph10">
    <div class="topbar-left">
        <ul class="nav nav-list nav-list-topbar pull-left">
            <li >
                <a href="#">Dashboard</a>
            </li>
            <li class="active">
                <a href="<?php echo $this->url('admin/default', array('controller' => 'product', 'action' => 'list')); ?>">Products</a>
            </li>
            <li>
                <a href="#">Orders</a>
            </li>
            <li>
                <a href="#">Customers</a>
            </li>
            <li>
                <a href="#">Settings</a>
            </li>
        </ul>
    </div>
    <div class="topbar-right">  
        <a href="<?php echo $this->url('admin/default', array('controller' => 'product', 'action' => 'add')); ?>" class="btn btn-default btn-sm light fw600 ml10"><span class="fa fa-plus pr5"></span> Add Product</a>
    </div>
</header>
<!-- End: Topbar -->

<!-- Begin: Content -->
<section id="content" class="table-layout animated fadeIn">

    <!-- begin: .tray-center -->
    <div class="tray tray-center p25 va-t posr">

        <!-- create new order panel -->
        <div class="panel mb25 mt5">
            <div class="panel-heading">
                <span class="panel-title"> Add New Product</span>
                <ul class="nav panel-tabs-border panel-tabs">
                    <li class="active">
                        <a href="#tab1_1" data-toggle="tab">Description</a>
                    </li>
                    <li>
                        <a href="#tab1_2" data-toggle="tab">Data</a>
                    </li>
                    <li>
                        <a href="#tab1_3" data-toggle="tab">Meta-Data</a>
                    </li>

                    <!--li>
                        <a href="#tab1_4" data-toggle="tab">Images</a>
                    </li-->
                    <li>
                        <a href="#tab1_5" data-toggle="tab">Stock</a>
                    </li>
                </ul>
            </div>
            <div class="panel-body p20 pb10 form-horizontal">     
                <form id="form"  action="<?php echo $this->basePath($this->productForm->getAttribute('action')); ?>" method="post" enctype="multipart/form-data" >   
                    <?php echo $this->formhidden($this->productForm->get('productId')) ?>
                    <div class="tab-content pn br-n admin-form theme-primary">  

                        <div id="tab1_1" class="tab-pane active">                           
                            <div class="section row mbn">
                                <div class="col-md-4">
                                    <div class="fileupload fileupload-new admin-form" data-provides="fileupload">
                                        <div class="fileupload-preview thumbnail mb20">
                                            <img data-src="holder.js/100%x140" alt="holder">
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-7 pr5">
                                                <input type="text" name="imgkey" id="imgkey" class="text-center gui-input" placeholder="Img Keywords">
                                                <label for="name2" class="field-icon"></label>
                                            </div>
                                            <div class="col-xs-5">
                                                <span class="button btn-system btn-file btn-block">
                                                    <span class="fileupload-new">Select</span>
                                                    <span class="fileupload-exists">Change</span>
                                                    <?php echo $this->formFile($this->productForm->get('productImage')); ?>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-8 pl15">

                                    <div class="section mb10 form-group ">

                                        <label class="col-lg-3 control-label" for="productName"> Nombre <span class="text-danger">*</span></label>

                                        <div class="col-md-8">
                                            <label for="productName" class="field prepend-icon">                                       
                                                <?php echo $this->formInput($this->productForm->get('productName')); ?>
                                                <label for="name2" class="field-icon"><i class="fa fa-tag"></i>
                                                </label>
                                            </label> 
                                            <div class="help-block">
                                                <?php echo $this->formelementerrors($this->productForm->get('productName')) ?> 
                                            </div>
                                        </div>     
                                    </div>
                                    <div class="section mb10 form-group">
                                        <label class="col-lg-3 control-label" for="productName">Descripción <span class="text-danger">*</span></label>
                                        <div class="col-md-8">
                                            <label class="field prepend-icon">
                                                <?php echo $this->formTextarea($this->productForm->get('productDescription')); ?>
                                                <label for="productDescription" class="field-icon"><i class="fa fa-comments"></i>
                                                </label>
                                                <span class="input-footer hidden ">
                                                    <strong>Hint</strong>Don't be negative or off topic! just be awesome...</span>
                                            </label>
                                            <div class="help-block">
                                                <?php echo $this->formelementerrors($this->productForm->get('productDescription')) ?> 
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>


                        </div>
                        <div id="tab1_2" class="tab-pane">
                            <div class="section row">

                                <div class="col-md-4 form-group">

                                    <label class="col-lg-3 control-label" for="productModel">Modelo <span class="text-danger">*</span></label>
                                    <div class="col-md-8"> 
                                        <label for="productModel" class="field prepend-icon">
                                            <?php echo $this->formInput($this->productForm->get('productModel')); ?>
                                            <label for="productModel" class="field-icon"><i class="fa fa-shopping-cart"></i>
                                            </label>
                                        </label>
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productModel')) ?> 
                                        </div>
                                    </div>
                                </div>

                                <!-- end section -->
                                <div class="col-md-4 form-group">

                                    <label class="col-lg-3 control-label" for="productModel">SKU </label>
                                    <div class="col-md-8"> 
                                        <label for="productSku" class="field prepend-icon">
                                            <?php echo $this->formInput($this->productForm->get('productSku')); ?>
                                            <label for="productSku" class="field-icon"><i class="fa fa-shopping-cart"></i>
                                            </label>
                                        </label>
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productSku')) ?> 
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 form-group">

                                    <label class="col-lg-3 control-label" for="productIsbn">ISBN </label>
                                    <div class="col-md-8"> 
                                        <label for="productIsbn" class="field prepend-icon">
                                            <?php echo $this->formInput($this->productForm->get('productIsbn')); ?>
                                            <label for="productIsbn" class="field-icon"><i class="fa fa-shopping-cart"></i>
                                            </label>
                                        </label>
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productIsbn')) ?> 
                                        </div>
                                    </div>
                                </div>
                                <!-- end section -->

                            </div>
                            <div class="section row">
                                <div class="col-md-4 form-group ">

                                    <label class="col-lg-3 control-label" for="productPrice">Precio <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                        <label for="productPrice" class="field prepend-icon">
                                            <?php echo $this->formInput($this->productForm->get('productPrice')); ?>
                                            <label for="productPrice" class="field-icon"><i class="fa fa-usd"></i>
                                            </label>
                                        </label>
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productPrice')) ?> 
                                        </div>
                                    </div>

                                </div>
                                <div class="col-md-4 form-group">

                                    <label class="col-lg-3 control-label" for="productStore">Pais <span class="text-danger">*</span></label>
                                    <div class="col-md-8 "> 
                                        <label class="field select">
                                            <?php echo $this->formSelect($this->productForm->get('productStore')) ?>
                                            <i class="arrow double "></i>
                                        </label>
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productStore')) ?> 
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-4 form-group ">

                                    <label class="col-lg-5 control-label" for="productMinimun">Orden Minima </label>
                                    <div class="col-md-7">
                                        <label for="productMinimun" class="field prepend-icon">
                                            <?php echo $this->formInput($this->productForm->get('productMinimun')); ?>
                                            <label for="productMinimun" class="field-icon"><i class="fa fa-shopping-cart"></i>
                                            </label>
                                        </label>
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productMinimun')) ?> 
                                        </div>
                                    </div>

                                </div>
                            </div>

                            <!-- end section row section -->


                            <!-- end section row section -->
                            <div class="section row">
                                <div class="col-md-4"> 
                                    <label class="col-md-3 control-label">Round Switches</label>
                                    <div class="switch switch-primary round switch-inline">
                                        <input id="exampleCheckboxSwitch7" type="checkbox" checked>
                                        <label for="exampleCheckboxSwitch7"></label>
                                    </div>
                                    <!-- end section -->
                                </div>
                            </div>
                        </div>
                        <div id="tab1_3" class="tab-pane">

                            <!-- end section -->

                            <div class="section row">
                                <div class="col-md-6 form-group">
                                    <label class="col-lg-3 control-label" for="productMetaTittle">Meta Titulo  <span class="text-danger">*</span></label>
                                    <div class="col-md-9">
                                        <label for="productMetaTittle" class="field prepend-icon">
                                            <?php echo $this->formInput($this->productForm->get('productMetaTittle')) ?> 
                                            <label for="productMetaTittle" class="field-icon"><i class=" fa fa-tag"></i>
                                            </label> 
                                        </label>  
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productMetaTittle')) ?> 
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 form-group">
                                    <label class="col-lg-3 control-label" for="productSeoUrl">SEO URL  <span class="text-danger">*</span></label>
                                    <div class="col-md-9">
                                        <label for="productSeoUrl" class="field prepend-icon">
                                            <?php echo $this->formInput($this->productForm->get('productSeoUrl')) ?> 
                                            <label for="productUrlSeo" class="field-icon"><i class=" fa fa-tag"></i>
                                            </label> 
                                        </label>  
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productSeoUrl')) ?> 
                                        </div>
                                    </div>
                                </div>



                            </div>
                            <div class="section row">
                                 <div class="col-md-6 form-group">
                                    <label class="col-lg-3 control-label" for="productCategories">Categorias  <span class="text-danger">*</span></label>
                                    <div class="col-md-9 form-group">

                                        <?php echo $this->formSelect($this->productForm->get('productCategories')) ?>
                                        
                                    </div>
                                </div>
                                <!-- end section -->
                                
                                <div class="col-md-6 form-group">
                                    <label class="col-lg-3 control-label" for="productTags">Tags  </label>
                                    <div class="col-md-9">
                                        <label for="productTags" class="field prepend-icon">
                                            <?php echo $this->formInput($this->productForm->get('productTags')) ?> 

                                        </label>  
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productTags')) ?> 
                                        </div>
                                    </div>
                                </div>
                                <!-- end section  -->
                               

                            </div>
                           
                            <div class="section row">

                                <div class="col-md-6 form-group">
                                    <label class="col-lg-3 control-label" for="productMetaDescription">Meta Descripción  </label>
                                    <div class="col-md-9">
                                        <label class="field prepend-icon">
                                            <?php echo $this->formTextarea($this->productForm->get('productMetaDescription')); ?>
                                            <label for="productDescription" class="field-icon"><i class="fa fa-comments"></i>
                                            </label>

                                        </label>
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productMetaDescription')) ?> 
                                        </div>
                                    </div>
                                </div>
                                <!-- end section -->

                                <div class="col-md-6 form-group">
                                    <label class="col-lg-3 control-label" for="productMetaKeywords">Meta Keywords  </label>
                                    <div class="col-md-9">
                                        <label class="field prepend-icon">
                                            <?php echo $this->formTextarea($this->productForm->get('productMetaKeywords')); ?>
                                            <label for="productDescription" class="field-icon"><i class="fa fa-comments"></i>
                                            </label>

                                        </label>
                                        <div class="help-block">
                                            <?php echo $this->formelementerrors($this->productForm->get('productMetaKeywords')) ?> 
                                        </div>
                                    </div>
                                </div>
                                <!-- end section -->


                            </div>
                            <!-- end section row section -->

                        </div>
                        <div id="tab1_4" class="tab-pane" style="height: 400px">
                            <div class="col-xs-12 col-sm-8 pl30">
                                <div class="tray-bin pl10 mb10" style="min-height: 250px;">
                                    <h5 class="text-muted mt10 fw600 pl10"><i class="fa fa-exclamation-circle text-info fa-lg pr10"></i> Portlet Drag and Drop Uploader </h5>
                                    <div class="dropzone dropzone-sm" id="dropzone">
                                        <div class="fallback">
                                            <input name="file-drop" type="file" multiple />
                                        </div>   
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="tab1_5" class="tab-pane">

                            <div class="multi-field-wrapper">
                                <div class="multi-fields">
                                    <div class="multi-field"> 

                                        <div class="section row">
                                            <div class="col-md-3 form-group ">

                                                <label class="col-lg-3 control-label" for="productQuantity">Cantidad </label>
                                                <div class="col-md-8">
                                                    <label for="productQuantity" class="field prepend-icon">
                                                        <?php echo $this->formInput($this->productForm->get('productQuantity')); ?>
                                                        <label for="productQuantity" class="field-icon"><i class="fa fa-barcode"></i>
                                                        </label>
                                                    </label>
                                                    <div class="help-block">
                                                        <?php echo $this->formelementerrors($this->productForm->get('productQuantity')) ?> 
                                                    </div>
                                                </div>

                                            </div>
                                            <div class="col-md-3 form-group">

                                                <label class="col-lg-3 control-label" for="productStock">Stock <span class="text-danger">*</span></label>
                                                <div class="col-md-8 "> 
                                                    <label class="field select">
                                                        <?php echo $this->formSelect($this->productForm->get('productStock')) ?>
                                                        <i class="arrow double "></i>
                                                    </label>
                                                    <div class="help-block">
                                                        <?php echo $this->formelementerrors($this->productForm->get('productStock')) ?> 
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-3 form-group">

                                                <label class="col-lg-5 control-label" for="productStockStatus">Estatus Stock  <span class="text-danger">*</span></label>
                                                <div class="col-md-7 "> 
                                                    <label class="field select">
                                                        <?php echo $this->formSelect($this->productForm->get('productStockStatus')) ?>
                                                        <i class="arrow double "></i>
                                                    </label>
                                                    <div class="help-block">
                                                        <?php echo $this->formelementerrors($this->productForm->get('productStockStatus')) ?> 
                                                    </div>
                                                </div>
                                            </div> 
                                            <div class="col-md-3 form-group ">
                                              <button type="button" class="remove-field">Remove</button>
                                           </div>
                                        </div>
                                    </div>

                                </div><button type="button" class="add-field">Add field</button>
                            </div>
                            <!--div class="section row">
                                <div class="col-md-3 form-group ">

                                    <label class="col-lg-3 control-label" for="productQuantity">Cantidad </label>
                                    <div class="col-md-8">
                                        <label for="productQuantity" class="field prepend-icon">
                            <?php echo $this->formInput($this->productForm->get('productQuantity')); ?>
                                            <label for="productQuantity" class="field-icon"><i class="fa fa-barcode"></i>
                                            </label>
                                        </label>
                                        <div class="help-block">
                            <?php echo $this->formelementerrors($this->productForm->get('productQuantity')) ?> 
                                        </div>
                                    </div>

                                </div>
                                <div class="col-md-3 form-group">

                                    <label class="col-lg-3 control-label" for="productStock">Stock <span class="text-danger">*</span></label>
                                    <div class="col-md-8 "> 
                                        <label class="field select">
                            <?php echo $this->formSelect($this->productForm->get('productStock')) ?>
                                            <i class="arrow double "></i>
                                        </label>
                                        <div class="help-block">
                            <?php echo $this->formelementerrors($this->productForm->get('productStock')) ?> 
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-4 form-group">

                                    <label class="col-lg-5 control-label" for="productStockStatus">Estatus Stock  <span class="text-danger">*</span></label>
                                    <div class="col-md-7 "> 
                                        <label class="field select">
                            <?php echo $this->formSelect($this->productForm->get('productStockStatus')) ?>
                                            <i class="arrow double "></i>
                                        </label>
                                        <div class="help-block">
                            <?php echo $this->formelementerrors($this->productForm->get('productStockStatus')) ?> 
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2 form-group">
                                    <button type="button" class="add-field btn-sm ">Add field</button>
                                </div>

                            </div-->
                        </div>
                        <input type="hidden" id="upload_images" name="upload_images[]" multiple />
                        <hr class="short alt">
                        <div class="panel-footer text-right">
                            <button class="btn btn-primary text-right"> Saved </button>
                        </div>
                </form>
            </div>
        </div>

    </div>


</section>
<style>
    /*dropzone demo css*/
    .dz-demo .dz-message {
        opacity: 0 !important;
    }
    .dropzone .dz-preview.example-preview .dz-success-mark,
    .dropzone-previews .dz-preview.example-preview .dz-success-mark {
        opacity: 1;
    }
    .dropzone .dz-preview.example-preview .dz-error-mark,
    .dropzone-previews .dz-preview.example-preview .dz-error-mark {
        opacity: 0;
    }
</style>
<?php
$this->headScript()
        ->prependFile($this->basePath() . '/vendor/plugins/fileupload/fileupload.js')
        ->prependFile($this->basePath() . '/vendor/plugins/tagsinput/tagsinput.min.js')
        ->prependFile($this->basePath() . '/vendor/plugins/dropzone/dropzone.min.js')
        ->prependFile($this->basePath() . '/vendor/plugins/select2/select2.min.js')
        ->prependFile($this->basePath() . '/assets_admin/js/bootstrap/holder.min.js')
        ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/advanced/steps/jquery.steps.js')
        ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/jquery.validate.min.js')
// ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/additional-methods.min.js')
;



$this->inlineScript()->captureStart();
echo <<<JS
   jQuery(document).ready(function() {
            $('.multi-field-wrapper').each(function() {
                var wrapper = $('.multi-fields', this);
                $(".add-field", $(this)).click(function(e) {
                $('.multi-field:first-child', wrapper).clone(true).appendTo(wrapper).find('input').val('').focus();
            });
            $('.multi-field .remove-field', wrapper).click(function() {
                if ($('.multi-field', wrapper).length > 1)
                $(this).closest('.multi-field').remove();
                });
            });
        

             // Dropzone autoattaches to "dropzone" class.
            // Configure Dropzone options
           Dropzone.autoDiscover = false;
            $("#dropzone").dropzone({
                init: function() {
                 //this.on("addedfile", function(file) { alert("Added file."); }); 
                 var myDropzone = this;

                   this.on("addedfile", function(file, xhr, data) {
                     // add headers with xhr.setRequestHeader() or
                     // form data with formData.append(name, value);
                     $("input[name='upload_images[]']").val('ver');
                   });
                 },
                paramName: 'upload_images',
                url: 'add',
                dictDefaultMessage: "Drag your images",
                clickable: true,
                addRemoveLinks: true,

                autoProcessQueue: false,
                uploadMultiple: true,
                
            });

            // grant file-upload preview onclick functionality
            $('.fileupload-preview').on('click', function() {
                $('.btn-file > input').click();
            });
            /*$('#multiselec').multiselect({
              enableFiltering: true,  
            });*/
            // Init Select2 - Basic Multiple
            $("#multiselect3").select2({
              placeholder: "Select Categories",
               allowClear: true,
               style: "bg-primary light"
            });
            $(".select2-multiple").select2({
              placeholder: "Select a state",
               allowClear: true
            });
            // select dropdowns - placeholder like creation
            var selectList = $('.admin-form select');
            selectList.each(function(i, e) {
                $(e).on('change', function() {
                    if ($(e).val() == "0") $(e).addClass("empty");
                    else $(e).removeClass("empty")
                });
            });
            selectList.each(function(i, e) {
                $(e).change();
            });

            // Init tagsinput plugin
            $("input#tagsinput").tagsinput({
                tagClass: function(item) {
                    return 'label bg-primary light';
                }
            });
        
           /* @custom validation method (smartCaptcha) 
            ------------------------------------------------------------------ */
                
            $.validator.methods.smartCaptcha = function(value, element, param) {
                    return value == param;
            };
            
            $.validator.addMethod("Alnum", function(value, element) {
             return this.optional(element) || /^[a-z0-9\s]+$/i.test(value);
            }, "Username must contain only letters, numbers, or dashes.");

            $.validator.addMethod("AlnumOf", function(value, element) {
             return this.optional(element) || /^[a-z0-9\-]+$/i.test(value);
            }, "Username must contain only letters, numbers, or dashes.");
                    
            $( "#form" ).validate({
            
                    /* @validation states + elements 
                    ------------------------------------------- */
                    
                    errorClass: "state-error",
                    validClass: "state-success",
                    errorElement: "em",
                    ignore: false,
                    
                    /* @validation rules 
                    ------------------------------------------ */
                        
                    rules: {
                            productName: {
                                    required: true,
                                    Alnum: true,
                            },
                            productDescription: {
                                    required: true
                            },                                                                
                            productModel: {
                                    required: true
                            },
                            productMetaTittle: {
                                    required: true,
                                    Alnum: true,
                            },
                            productSeoUrl: {
                                    required: true,
                                    AlnumOf: true,
                            },
                            productCategories: {
                                    required: true
                            },  
                                
                        
                    },
                    
                    /* @validation error messages 
                    ---------------------------------------------- */
                        
                    messages:{
                            productName: {
                                    required: 'Campo Obligatorio',
                                    Alnum: 'Solo letras y numeros'
                            },
                            productDescription: {
                                    required: 'Campo Obligatorio'
                            },                  
                            productCategories: {
                                    required: 'Campo Obligatorio'
                            },                  
                            productModel: {
                                    required: 'Campo Obligatorio'
                            },                  
                            productMetaTittle: {
                                    required: 'Campo Obligatorio',
                                    Alnum: 'Solo letras y numeros'
                            },                  
                            productSeoUrl: {
                                    required: 'Campo Obligatorio',
                                    AlnumOf: 'Solo letras, numeros y guion '
                            },                  
                           
                    },

                    /* @validation highlighting + error placement  
                    ---------------------------------------------------- */ 
                    
                    highlight: function(element, errorClass, validClass) {
                            $(element).closest('.field').addClass(errorClass).removeClass(validClass);
                    },
                    invalidHandler: function(e,validator) {
                        // loop through the errors:                
                          $('.tab-pane').closest('.active').removeClass('active');
                          $('.panel-tabs li').closest('.active').removeClass('active');
                            // "uncollapse" section containing invalid input/s:
                            $(validator.errorList[0].element).closest('.tab-pane').addClass('active');
                            tab =  $(validator.errorList[0].element).closest('.tab-pane').attr('id');
                            tab ='#'+tab;
                          $('a[href='+tab+']').closest('li').addClass('active');
                        
                    },
                    unhighlight: function(element, errorClass, validClass) {
                            $(element).closest('.field').removeClass(errorClass).addClass(validClass);
                    },
                    errorPlacement: function(error, element) {
                       if (element.is(":radio") || element.is(":checkbox")) {
                                element.closest('.option-group').after(error);
                       } else {
                                error.insertAfter(element.parent());
                       }
                    }
                            
            });     
        
        

        });
JS;
$this->inlineScript()->captureEnd();
