<!-- Start: Topbar -->
<header id="topbar" class="ph10">
    <div class="topbar-left">
        <ul class="nav nav-list nav-list-topbar pull-left">
            <li >
                <a href="#">Dashboard</a>
            </li>
            <li class="active">
                <a href="<?php echo $this->url('admin/default', array('controller' => 'product', 'action' => 'list')); ?>">Products</a>
            </li>
            <li>
                <a href="#">Orders</a>
            </li>
            <li>
                <a href="#">Customers</a>
            </li>
            <li>
                <a href="#">Settings</a>
            </li>
        </ul>
    </div>
    <div class="topbar-right">  
        <a href="<?php echo $this->url('admin/default', array('controller' => 'product', 'action' => 'add')); ?>" class="btn btn-default btn-sm light fw600 ml10"><span class="fa fa-plus pr5"></span> Add Product</a>
    </div>
</header>
<!-- End: Topbar -->

<!-- Begin: Content -->
<section id="content" class="table-layout animated fadeIn">

    <!-- begin: .tray-center -->
    <div class="tray tray-center p25 va-t posr">

        <!-- create new order panel -->
        <div class="panel mb25 mt5">
            <div class="panel-heading">
                <span class="panel-title"> Add New Product</span>
                <ul class="nav panel-tabs-border panel-tabs">
                    <li class="active">
                        <a href="#tab1_1" data-toggle="tab">General</a>
                    </li>
                    <li>
                        <a href="#tab1_2" data-toggle="tab">Description</a>
                    </li>
                    <li>
                        <a href="#tab1_3" data-toggle="tab">Description</a>
                    </li>
                </ul>
            </div>
            <div class="panel-body p20 pb10">
                <form id="form"  action="<?php echo $this->basePath($this->productForm->getAttribute('action')); ?>" method="post">
                <?php echo $this->formhidden($this->productForm->get('productId'))?>
                    <div class="tab-content pn br-n admin-form theme-primary">  
                        <div id="tab1_1" class="tab-pane active">
                            <div class="section row mbn">
                                <div class="col-md-4">
                                    <div class="fileupload fileupload-new admin-form" data-provides="fileupload">
                                        <div class="fileupload-preview thumbnail mb20">
                                            <img data-src="holder.js/100%x140" alt="holder">
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-7 pr5">
                                                <input type="text" name="imgkey" id="imgkey" class="text-center gui-input" placeholder="Img Keywords">
                                                <label for="name2" class="field-icon"></label>
                                            </div>
                                            <div class="col-xs-5">
                                                <span class="button btn-system btn-file btn-block">
                                                    <span class="fileupload-new">Select</span>
                                                    <span class="fileupload-exists">Change</span>
                                                    <input type="file">
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-8 pl15">
                                    <div class="section mb10 form-group">
                                        <label for="productName" class="field prepend-icon">
                                            <?php echo $this->formInput($this->productForm->get('productName'));?>
                                            <label for="name2" class="field-icon"><i class="fa fa-tag"></i>
                                            </label>
                                        </label>
                                         <div class="help-block">
                                           <?php echo $this->formelementerrors($this->productForm->get('productName'))?> 
                                         </div>
                                    </div>
                                    <div class="section mb10">
                                        <label class="field prepend-icon">
                                           <?php echo $this->formTextarea($this->productForm->get('productDescription')); ?>
                                            <label for="productDescription" class="field-icon"><i class="fa fa-comments"></i>
                                            </label>
                                            <span class="input-footer hidden">
                                                <strong>Hint:</strong>Don't be negative or off topic! just be awesome...</span>
                                        </label>
                                    </div>
                                </div>

                            </div>


                        </div>
                        <div id="tab1_2" class="tab-pane">
                            <div class="section row">
                                <div class="col-md-6">
                                    <label for="product-category" class="field select">
                                        <select id="product-category" name="product-category">
                                            <option value="0" selected="selected">Product Category...</option>
                                            <option value="1">Software</option>
                                            <option value="2">Computers</option>
                                            <option value="3">Gadgets</option>
                                            <option value="4">Clothing</option>
                                        </select>
                                        <i class="arrow double"></i>
                                    </label>
                                </div>
                                <!-- end section -->

                                <div class="col-md-6">
                                    <label class="field select">
                                        <select id="product-status" name="product-status">
                                            <option value="0" selected="selected">Product Availability</option>
                                            <option value="1">Available</option>
                                            <option value="2">Unavailable</option>
                                            <option value="3">Discontinued</option>
                                            <option value="4">Out of Stock</option>
                                        </select>
                                        <i class="arrow double"></i>
                                    </label>
                                </div>
                                <!-- end section -->

                            </div>
                            <!-- end section row section -->

                            <div class="section row">
                                <div class="col-md-4">
                                    <label for="product-price" class="field prepend-icon">
                                        <?php echo $this->formInput($this->productForm->get('productPrice')); ?>
                                        <label for="productPrice" class="field-icon"><i class="fa fa-usd"></i>
                                        </label>
                                    </label>
                                </div>
                                <!-- end section -->

                                <div class="col-md-4">
                                    <label for="product-vendor" class="field prepend-icon">
                                        <?php echo $this->formInput($this->productForm->get('productModel')); ?>
                                        <label for="productModel" class="field-icon"><i class="fa fa-shopping-cart"></i>
                                        </label>
                                    </label>
                                </div>
                                <!-- end section -->

                                <div class="col-md-4">
                                    <label for="product-sku" class="field prepend-icon">
                                        <input type="text" name="product-sku" id="product-sku" class="gui-input" placeholder="Product SKU...">
                                        <label for="product-sku" class="field-icon"><i class="fa fa-barcode"></i>
                                        </label>
                                    </label>
                                </div>
                                <!-- end section -->

                            </div>
                            <!-- end section row section -->

                            <div class="section">
                                <input id="tagsinput" type="text" value="Software, Adobe, Photoshop, Editor, Commercial">
                            </div>
                            <!-- end section row section -->

                            <hr class="short alt">

                            <div class="section row mbn">
                                <div class="col-sm-8">
                                    <label class="field option mt10">
                                        <input type="checkbox" name="info" checked>
                                        <span class="checkbox"></span>Save Customer
                                        <em class="small-text text-muted">- A Random Unique ID will be generated</em>
                                    </label>
                                </div>
                                <div class="col-sm-4">
                                    <p class="text-right">
                                        <button class="btn btn-primary" type="button">Save Order</button>
                                    </p>
                                </div>
                            </div>
                            <!-- end section -->

                        </div>
                        <div id="tab1_3" class="tab-pane">

                            <div class="section">
                                <label for="lastaddr" class="field prepend-icon">
                                    <input type="text" name="lastaddr" id="lastaddr" class="gui-input" placeholder="Street address 2">
                                    <label for="lastaddr" class="field-icon"><i class="fa fa-map-marker"></i>
                                    </label>
                                </label>
                            </div>
                            <!-- end section -->

                            <div class="section">
                                <label class="field select">
                                    <select id="location" name="location">
                                        <option value="">Select country...</option>
                                        <option value="AL">Albania</option>
                                        <option value="DZ">Algeria</option>
                                        <option value="AD">Andorra</option>
                                        <option value="AO">Angola</option>
                                        <option value="AI">Anguilla</option>
                                        <option value="AG">Antigua and Barbuda</option>
                                        <option value="AR">Argentina</option>
                                        <option value="AM">Armenia</option>
                                        <option value="AW">Aruba</option>
                                        <option value="AU">Australia</option>
                                        <option value="AT">Austria</option>



                                    </select>
                                    <i class="arrow double"></i>
                                </label>
                            </div>
                            <!-- end section -->

                            <div class="section row">
                                <div class="col-md-3">
                                    <label for="zip" class="field prepend-icon">
                                        <input type="text" name="zip" id="zip" class="gui-input" placeholder="Zip">
                                        <label for="zip" class="field-icon"><i class="fa fa-certificate"></i>
                                        </label>
                                    </label>
                                </div>
                                <!-- end section -->

                                <div class="col-md-4">
                                    <label for="city" class="field prepend-icon">
                                        <input type="text" name="city" id="city" class="gui-input" placeholder="City">
                                        <label for="city" class="field-icon"><i class="fa fa-building-o"></i>
                                        </label>
                                    </label>
                                </div>
                                <!-- end section -->

                                <div class="col-md-5">
                                    <label for="states" class="field select">
                                        <select id="states" name="states">
                                            <option value="">Choose state</option>
                                            <option value="AL">Alabama</option>
                                            <option value="AK">Alaska</option>
                                            <option value="AZ">Arizona</option>
                                            <option value="AR">Arkansas</option>
                                            <option value="CA">California</option>


                                        </select>
                                        <i class="arrow double"></i>
                                    </label>
                                </div>
                                <!-- end .col8 section -->

                            </div>
                            <!-- end section row section -->

                        </div>

                    </div> 
                    <hr class="short alt">
                    <div class="panel-footer text-right">
                        <button class="btn btn-primary text-right"> Saved </button>
                    </div>
                </form>
            </div>
        </div>

    </div>


</section>

<?php
$this->headScript()
        ->prependFile($this->basePath() . '/vendor/plugins/fileupload/fileupload.js')
        ->prependFile($this->basePath() . '/vendor/plugins/tagsinput/tagsinput.min.js')
        ->prependFile($this->basePath() . '/assets_admin/js/bootstrap/holder.min.js')
        ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/advanced/steps/jquery.steps.js')
        ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/jquery.validate.min.js')
        ->prependFile($this->basePath() . '/assets_admin/admin-tools/admin-forms/js/additional-methods.min.js')
;



$this->inlineScript()->captureStart();
 echo <<<JS
   jQuery(document).ready(function() {

            // grant file-upload preview onclick functionality
            $('.fileupload-preview').on('click', function() {
                $('.btn-file > input').click();
            });

            // select dropdowns - placeholder like creation
            var selectList = $('.admin-form select');
            selectList.each(function(i, e) {
                $(e).on('change', function() {
                    if ($(e).val() == "0") $(e).addClass("empty");
                    else $(e).removeClass("empty")
                });
            });
            selectList.each(function(i, e) {
                $(e).change();
            });

            // Init tagsinput plugin
            $("input#tagsinput").tagsinput({
                tagClass: function(item) {
                    return 'label bg-primary light';
                }
            });
        
           /* @custom validation method (smartCaptcha) 
            ------------------------------------------------------------------ */
                
            $.validator.methods.smartCaptcha = function(value, element, param) {
                    return value == param;
            };
            
            $.validator.addMethod("Alnum", function(value, element) {
             return this.optional(element) || /^[a-z0-9\-\s]+$/i.test(value);
            }, "Username must contain only letters, numbers, or dashes.");
                    
            $( "#form" ).validate({
            
                    /* @validation states + elements 
                    ------------------------------------------- */
                    
                    errorClass: "state-error",
                    validClass: "state-success",
                    errorElement: "em",
                    ignore: false,
                    
                    /* @validation rules 
                    ------------------------------------------ */
                        
                    rules: {
                            productName: {
                                    required: true,
                                    Alnum: true,
                            },
                            productDescription: {
                                    required: true
                            },                                                                
                            productModel: {
                                    required: true
                            },                                                                
                        
                    },
                    
                    /* @validation error messages 
                    ---------------------------------------------- */
                        
                    messages:{
                            productName: {
                                    required: 'Campo Obligatorio',
                                    Alnum: 'Solo letras y numeros'
                            },
                            productDescription: {
                                    required: 'Campo Obligatorio'
                            },                  
                            productModel: {
                                    required: 'Campo Obligatorio'
                            },                  
                           
                    },

                    /* @validation highlighting + error placement  
                    ---------------------------------------------------- */ 
                    
                    highlight: function(element, errorClass, validClass) {
                            $(element).closest('.field').addClass(errorClass).removeClass(validClass);
                    },
                    invalidHandler: function(e,validator) {
                        // loop through the errors:                
                          $('.tab-pane').closest('.active').removeClass('active');
                          $('.panel-tabs li').closest('.active').removeClass('active');
                            // "uncollapse" section containing invalid input/s:
                            $(validator.errorList[0].element).closest('.tab-pane').addClass('active');
                            tab =  $(validator.errorList[0].element).closest('.tab-pane').attr('id');
                            tab ='#'+tab;
                          $('a[href='+tab+']').closest('li').addClass('active');
                        
                    },
                    unhighlight: function(element, errorClass, validClass) {
                            $(element).closest('.field').removeClass(errorClass).addClass(validClass);
                    },
                    errorPlacement: function(error, element) {
                       if (element.is(":radio") || element.is(":checkbox")) {
                                element.closest('.option-group').after(error);
                       } else {
                                error.insertAfter(element.parent());
                       }
                    }
                            
            });     
        
        

        });
JS;
$this->inlineScript()->captureEnd();
