<!-- Start: Topbar -->
<header id="topbar" class="ph10">
    <div class="topbar-left">
        <ul class="nav nav-list nav-list-topbar pull-left">
            <li >
                <a href="#">Dashboard</a>
            </li>
            <li class="active">
                <a href="<?php echo $this->url('admin', array('controller' => 'product', 'action' => 'list')); ?>">Products</a>
            </li>
            <li>
                <a href="#">Orders</a>
            </li>
            <li>
                <a href="#">Customers</a>
            </li>
            <li>
                <a href="#">Settings</a>
            </li>
        </ul>
    </div>
    <div class="topbar-right">  
        <a href="<?php echo $this->url('admin', array('controller' => 'product', 'action' => 'add')); ?>" class="btn btn-primary btn-sm light fw600 ml10"><span class="fa fa-plus pr5"></span> Add Product</a>
    </div>
</header>
<!-- End: Topbar -->
<section class="table-layout" id="content">
    <div class="panel p">
        <div class="panel-body pn col-lg-11 col-md-11 col-sm-11">
            
            <table class="table admin-form theme-warning tc-checkbox-1 fs13">
                <thead>
                    <tr class="bg-light">
                        <th class="text-center">Select</th>
                        
                        <th class="">Image</th>
                        <th class="text-center">ID</th>
                        <th class="">Product Title</th>
                        <th class="">SKU</th>
                        <th class="">Price</th>
                        <th class="">Stock</th>
                        <th class="text-right">Status</th>

                    </tr>
                </thead>
                <tbody>
                 <?php foreach ($this->products as $product) : ?>
                
             
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <a href="<?php echo $this->basePath().'/catalogo/'.$product->getUrlAlias()->keyword;?>" target="_blank"> 
                                <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets') ?>/images/products/catalog/<?php echo $product->getImage();?>">
                            </a>
                        </td>
                        <td class="w50 text-center"><?php echo $product->getProductId();?></td>
                        <td class=""><?php echo $product->getProductDescription()->getName();?></td>
                        <td class="">#21362</td>
                        <td class=""><?php echo $product->getPrice();?></td>
                        <td class="">1,400</td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-success br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="true"> 
                                    Active
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="<?php echo $this->basePath().'/admin/product/edit/'.$product->getProductId();?>">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                     <?php endforeach; ?> 
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets_admin') ?>/img/stock/products/thumb_2.jpg">
                        </td>
                        <td class="">Apple Smart Watch - 1G</td>
                        <td class="">#15262</td>
                        <td class="">$455</td>
                        <td class="">2,100</td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-success br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Active
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets_admin') ?>/img/stock/products/thumb_6.jpg">
                        </td>
                        <td class="">Apple Macbook 4th Gen - Silver</td>
                        <td class="">#66362</td>
                        <td class="">$1699</td>
                        <td class="">6,100</td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-success br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Active
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets_admin') ?>/img/stock/products/thumb_7.jpg">
                        </td>
                        <td class="">Apple Iphone 16GB - Silver</td>
                        <td class="">#51362</td>
                        <td class="">$1299</td>
                        <td class="">5,200</td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-success br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Active
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets_admin') ?>/img/stock/products/thumb_3.jpg">
                        </td>
                        <td class="">Apple Ipod Nano 2G - Silver</td>
                        <td class="">#4132</td>
                        <td class="">$995</td>
                        <td class="">11,000</td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-success br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Active
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets_admin') ?>/img/stock/products/thumb_4.jpg">
                        </td>
                        <td class="">Apple Macbook 3rd Gen - Silver</td>
                        <td class="">#21362</td>
                        <td class="">$1,150</td>
                        <td class="">4,300</td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-success br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Active
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets_admin') ?>/img/stock/products/thumb_2.jpg">
                        </td>
                        <td class="">Apple Smart Watch - 1G</td>
                        <td class="">#15262</td>
                        <td class="">$455</td>
                        <td class="text-warning"><b>145</b>
                        </td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-warning br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Disabled
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets_admin') ?>/img/stock/products/thumb_5.jpg">
                        </td>
                        <td class="">Apple iMac 32" - Silver</td>
                        <td class="">#21362</td>
                        <td class="">$1299</td>
                        <td class="text-warning"><b>180</b>
                        </td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-warning br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Disabled
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets_admin') ?>/img/stock/products/thumb_3.jpg">
                        </td>
                        <td class="">Apple Ipod Nano 2G - Silver</td>
                        <td class="">#4132</td>
                        <td class="">$995</td>
                        <td class="text-danger"><b>0 - Sold Out</b>
                        </td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-danger br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Sold Out
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets_admin') ?>/img/stock/products/thumb_6.jpg">
                        </td>
                        <td class="">Apple Macbook 4th Gen - Silver</td>
                        <td class="">#66362</td>
                        <td class="">$1699</td>
                        <td class="text-danger"><b>0 - Sold Out</b>
                        </td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-danger br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Sold Out
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <label class="option block mn">
                                <input type="checkbox" name="mobileos" value="FR">
                                <span class="checkbox mn"></span>
                            </label>
                        </td>
                        <td class="w100">
                            <img class="img-responsive mw60 ib mr10" title="user" src="<?php echo $this->basePath('assets_admin') ?>/img/stock/products/thumb_7.jpg">
                        </td>
                        <td class="">Apple Iphone 16GB - Silver</td>
                        <td class="">#51362</td>
                        <td class="">$1299</td>
                        <td class="text-danger"><b>0 - Sold Out</b>
                        </td>
                        <td class="text-right">
                            <div class="btn-group text-right">
                                <button type="button" class="btn btn-danger br2 btn-xs fs12 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Sold Out
                                    <span class="caret ml5"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#">Delete</a>
                                    </li>
                                    <li>
                                        <a href="#">Archive</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Complete</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">Pending</a>
                                    </li>
                                    <li>
                                        <a href="#">Canceled</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

</section>