<?php
echo $this->headlink() 
        ->appendStylesheet($this->basePath('assets') . '/css/index.css');

        $images = $this->basePath('assets') . '/images/test/';
?>

<div class="container">

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img class="img-responsive" src="assets/images/sliders/slide1-1800x930.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img class="img-responsive" src="assets/images/sliders/slide2-1800x930.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img class="img-responsive" src="assets/images/sliders/slide3-1800x930.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<hr>
    <div id="carousel-best" class="best-seller-3">
        <!-- Carousel items -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_wood_puzzle-430x480.jpg' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_tina_frey_dishes1-430x480.jpg ' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_sphrical_vase-430x480.jpg ' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_chrome_pen-430x480.jpg' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_wood_puzzle-430x480.jpg' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_112_hario_glasses_4-430x480.jpg' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
    </div>

    <hr>

    <div id="carousel-nuevos" class="best-seller-2">
        <!-- Carousel items -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_aalto_vase-430x480.jpg' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_hasami_lids-430x480.jpg' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_hanging_planter-430x480.jpg' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_super_normal-430x480.jpg' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_tina_frey_dishes1-430x480.jpg' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
            <div class="item">
                <div class="thumbnail">          
                    <div class="caption">       
                        <div class="row"><div class="col-md-12"><p>Sofa Minimalista</p></div></div>
                        <div class="row">
                            <div class="col-md-8 col-xs-8">
                                <div class="btn-group"> 
                                    <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> </a>
                                    <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a href="#" class="btn btn-default btn-product"><span class="glyphicon glyphicon-share"></span> </a>
                                </div>
                            </div>
                        <div class="col-md-4 col-xs-4 price"><label>$649.99</label></div>
                        </div> <!-- row -->              
                    </div> <!-- caption -->            
                    <img src="<?=$images . 'yes_thumbs_vase-443x500-430x480.jpg' ?>" class="img-responsive" />
                </div> <!-- thumbnail -->
            </div>
            <!-- item -->
    </div>

</div>
