<?php
echo $this->headlink() 
        ->appendStylesheet($this->basePath('assets') . '/css/index.min.css');
?>

<div class="container">

<div id="carousel-example-generic" class="carousel slide hidden-xs" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img class="img-responsive" src="assets/images/sliders/slide1-1800x930.jpg" alt="...">
      <div class="carousel-caption"></div>
    </div>
    <div class="item">
      <img class="img-responsive" src="assets/images/sliders/slide2-1800x930.jpg" alt="...">
      <div class="carousel-caption"></div>
    </div>
    <div class="item">
      <img class="img-responsive" src="assets/images/sliders/slide3-1800x930.jpg" alt="...">
      <div class="carousel-caption"> </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    <hr>
    <div class='row'>
        <div class='col-xs-3'>
            <div class='promo-space'>
                <div class='promo-image'>
                    <img class='img-responsive' src='<?php echo $this->basePath('assets/images/avion_promo.png');?>'>
                </div>
                <div class='promo-description'>
                    <span class='promo-name'><span style='color:green'>ENVIO GRATIS @</span> Cualquier precio</span>
                    <span class='promo-text'>con entrega 3-8 dias en todo el mundo.</span>
                </div>
            </div>
        </div>
        <div class='col-xs-3'>
            <div class='promo-space'>
                <div class='promo-image'>
                    <img class='img-responsive' src='<?php echo $this->basePath('assets/images/calendario_promo.png');?>'>
                </div>
                <div class='promo-description'>
                    <span class='promo-name'>30 Dias politicas de devoluciones</span>
                    <span class='promo-text'>Su Satisfacción es nuestra maxima prioridad.</span>
                </div>
            </div>
        </div>
        <div class='col-xs-3'>
            <div class='promo-space'>
                <div class='promo-image'>
                    <img class='img-responsive' src='<?php echo $this->basePath('assets/images/cochinito_promo.png');?>'>
                </div>
                <div class='promo-description'>
                    <span class='promo-name'><span style='color:red'>Diseño de fabrica @</span> Cualquier precio</span>
                    <span class='promo-text'>con garatia de alta calidad.</span>
                </div>
            </div>
        </div>
        <div class='col-xs-3'>
            <div class='promo-space'>
                <div class='promo-image'>
                    <img class='img-responsive' src='<?php echo $this->basePath('assets/images/chat_promo.png');?>'>
                </div>
                <div class='promo-description'>
                    <span class='promo-name'><span style=''>Live chat</span></span>
                    <span class='promo-text'>9.am- 6:30px horas GMT +8 lunes a sabado.</span>
                </div>
            </div>
        </div>
    </div>
    <div class='row'>
        <div class='col-xs-6'>
            <img style='width: 100%; margin: 0 auto;' class='img-responsive' src='<?php echo $this->basePath('assets/images/sillas_promocion.png');?>' />
        </div>
        <div class='col-xs-6'>
            <img style='width: 100%;margin: 0 auto;' class='img-responsive' src='<?php echo $this->basePath('assets/images/lamparas_romocion.png');?>' />
        </div>
    </div>
    <hr>
    <div id="slider-products" class="slider-owl"></div>
</div>

<script type='application/json' id='bestSellerJSON'>
    <?php echo $this->bestSeller ?>
</script>

<script type='application/json' id='latestJSON'>
    <?php echo $this->latest ?>
</script>

<?php $urlAjax = $this->url('application', array('controller' => 'index'));  

$this->inlineScript()->captureStart();

 echo <<<JS
   var URL_AJAX = '{$urlAjax}';
JS;

$this->inlineScript()->captureEnd();
$this->inlineScript()->appendFile($this->basePath('/assets/js/dist/index.min.js'));
