<?php
echo $this->headlink() 
        ->appendStylesheet($this->basePath('assets') . '/css/index.min.css');
?>

<div class="container">

<div id="carousel-example-generic" class="carousel slide hidden-xs" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img class="img-responsive" src="assets/images/sliders/slide1-1800x930.jpg" alt="...">
      <div class="carousel-caption"></div>
    </div>
    <div class="item">
      <img class="img-responsive" src="assets/images/sliders/slide2-1800x930.jpg" alt="...">
      <div class="carousel-caption"></div>
    </div>
    <div class="item">
      <img class="img-responsive" src="assets/images/sliders/slide3-1800x930.jpg" alt="...">
      <div class="carousel-caption"> </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

    <hr>
    <div id="slider-products" class="slider-owl">
    </div>
</div>

<script type='application/json' id='bestSellerJSON'>
    <?php echo $this->bestSeller ?>
</script>

<script type='application/json' id='latestJSON'>
    <?php echo $this->latest ?>
</script>

<?php $urlAjax = $this->url('application', array('controller' => 'index'));  

$this->inlineScript()->captureStart();

 echo <<<JS
   var URL_AJAX = '{$urlAjax}';
JS;

$this->inlineScript()->captureEnd();
$this->inlineScript()->appendFile($this->basePath('/assets/js/dist/index.min.js'));
